In [1]:
import pandas as pd
import json

In [2]:
with open("./cell_phones_survey.json", "r", encoding="utf-8-sig") as f:
    data = json.load(f)

df = pd.DataFrame(data)

In [3]:
with open("./github.json", "r", encoding="utf-8-sig") as github:
     github_df = json.load(github)

df = pd.DataFrame(github_df)
df

,owner,name,stars,forks,watchers,isFork,languages,description,createdAt,pushedAt,license
0,pelmers,text-rewriter,11,4,3,False,"{'name': 'JavaScript', 'size': 21769}",Webextension to rewrite phrases in pages,2015-03-14T22:35:11Z,2022-02-11T14:26:00Z,None
1,pelmers,text-rewriter,11,4,3,False,"{'name': 'HTML', 'size': 2096}",Webextension to rewrite phrases in pages,2015-03-14T22:35:11Z,2022-02-11T14:26:00Z,None
2,pelmers,text-rewriter,11,4,3,False,"{'name': 'CSS', 'size': 2081}",Webextension to rewrite phrases in pages,2015-03-14T22:35:11Z,2022-02-11T14:26:00Z,None

In [4]:
df1 = pd.read_csv("./fifa_players.csv", low_memory=False)

In [5]:
index_col = "sofifa_id"
pd.read_csv("./fifa_players.csv",low_memory=False)

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,100500000.0,550000.0,27,...,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png,https://cdn.sofifa.net/teams/241/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,79000000.0,375000.0,29,...,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png,https://cdn.sofifa.net/teams/243/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
2,9014,https://sofifa.com/player/9014/arjen-robben/15...,A. Robben,Arjen Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,...,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/105035/60.png,https://cdn.sofifa.net/flags/nl.png
3,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,52500000.0,275000.0,32,...,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1363/60.png,https://cdn.sofifa.net/flags/se.png
4,167495,https://sofifa.com/player/167495/manuel-neuer/...,M. Neuer,Manuel Peter Neuer,GK,90,90,63500000.0,300000.0,28,...,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1337/60.png,https://cdn.sofifa.net/flags/de.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,220806,https://sofifa.com/player/220806/ellis-redman/...,E. Redman,Ellis Redman,CB,41,61,20000.0,2000.0,17,...,41,41,41,40,10,https://cdn.sofifa.net/players/220/806/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16151,225509,https://sofifa.com/player/225509/aaron-collins...,A. Collins,Aaron Graham John Collins,ST,41,50,30000.0,2000.0,17,...,31,31,31,32,14,https://cdn.sofifa.net/players/225/509/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16152,201197,https://sofifa.com/player/201197/paul-tisdale/...,P. Tisdale,Paul Tisdale,"CM, CAM",40,40,NaN,2000.0,41,...,33,33,33,34,10,https://cdn.sofifa.net/players/201/197/15_120.png,https://cdn.sofifa.net/teams/143/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/mt.png
16153,217591,https://sofifa.com/player/217591/piotr-zemlo/1...,P. Żemło,Piotr Żemło,"LM, LB",40,50,15000.0,2000.0,18,...,53-3,53-3,53-3,51-1,12,https://cdn.sofifa.net/players/217/591/15_120.png,https://cdn.sofifa.net/teams/1873/60.png,https://cdn.sofifa.net/flags/pl.png,NaN,https://cdn.sofifa.net/flags/pl.png
16154,222947,https://sofifa.com/player/222947/tom-davies/15...,T. Davies,Thomas Christopher Davies,CB,40,49,15000.0,2000.0,22,...,40,40,40,39,13,https://cdn.sofifa.net/players/222/947/15_120.png,https://cdn.sofifa.net/teams/112260/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-eng.png

In [1]:
pd.set_option("display.max_columns", 150)
df1

NameError: name 'pd' is not defined

In [7]:
pd.set_option("display.max_colwidth", 500)
df1

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/150002,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,100500000.0,550000.0,27,1987-06-24,169,67,241.0,FC Barcelona,Spain Primera Division,1.0,CF,10.0,NaN,2004-07-01,2018.0,52,Argentina,1369.0,CF,10.0,Left,3,4,5,Medium/Low,Normal (170-),Yes,NaN,"#Speedster, #Dribbler, #FK Specialist, #Acrobat, #Clinical Finisher, #Complete Forward","Finesse Shot, Speed Dribbler (AI), One Club Player, Team Player",93.0,89.0,86.0,96.0,27.0,63.0,84,94,71,89,85,96,89,90,76,96,96,90,94,94,95,80,73,77,60,88,48,22,92,90,76,NaN,25,21,20,6,11,15,14,8,NaN,89+3,89+3,89+3,92+3,90+3,90+3,90+3,92+3,92+3,92+3,92+3,90+3,79+3,79+3,79+3,90+3,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png,https://cdn.sofifa.net/teams/241/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/150002,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,79000000.0,375000.0,29,1985-02-05,185,80,243.0,Real Madrid CF,Spain Primera Division,1.0,LW,7.0,NaN,2009-07-01,2018.0,38,Portugal,1354.0,LW,7.0,Right,4,5,5,High/Low,Normal (185+),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat, #Clinical Finisher, #Complete Forward","Power Free-Kick, Flair, Long Shot Taker (AI), Speed Dribbler (AI)",93.0,93.0,81.0,91.0,32.0,79.0,83,95,86,82,87,93,88,79,72,92,91,94,93,90,63,94,94,89,79,93,63,24,91,81,85,NaN,22,31,23,7,11,15,14,11,NaN,91+1,91+1,91+1,89+3,91+1,91+1,91+1,89+3,89+3,89+3,89+3,87+3,77+3,77+3,77+3,87+3,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png,https://cdn.sofifa.net/teams/243/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
2,9014,https://sofifa.com/player/9014/arjen-robben/150002,A. Robben,Arjen Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,1984-01-23,180,80,21.0,FC Bayern München,German 1. Bundesliga,1.0,SUB,10.0,NaN,2009-08-28,2017.0,34,Netherlands,105035.0,RS,11.0,Left,2,4,5,High/Low,Normal (170-185),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat","Diver, Injury Prone, Avoids Using Weaker Foot, Selfish, Long Shot Taker (AI), Speed Dribbler (AI), Chip Shot (AI)",93.0,86.0,83.0,92.0,32.0,64.0,80,85,50,86,86,93,85,83,76,90,93,93,93,89,91,86,61,78,65,90,47,39,89,84,80,NaN,29,26,26,10,8,11,5,15,NaN,84+3,84+3,84+3,88+2,87+3,87+3,87+3,88+2,88+2,88+2,88+2,87+3,78+3,78+3,78+3,87+3,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/105035/60.png,https://cdn.sofifa.net/flags/nl.png
3,41236,https://sofifa.com/player/41236/zlatan-ibrahimovic/150002,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,52500000.0,275000.0,32,1981-10-03,195,95,73.0,Paris Saint-Germain,French Ligue 1,1.0,ST,10.0,NaN,2012-07-01,2016.0,46,Sweden,1363.0,ST,10.0,Right,4,4,5,Medium/Low,Normal (185+),Yes,NaN,"#Poacher, #Aerial Threat, #Distance Shooter, #Acrobat, #Strength, #Clinical Finisher, #Complete Forward","Power Free-Kick, Leadership, Flair, Long Shot Taker (AI), Technical Dribbler (AI)",76.0,91.0,81.0,86.0,34.0,86.0,76,91,76,84,92,88,80,80,76,90,74,77,86,85,41,93,72,78,93,88,84,20,86,83,91,NaN,25,41,27,13,15,10,9,12,NaN,87+3,87+3,87+3,84+3,86+3,86+3,86+3,84+3,86+3,86+3,86+3,83+3,76+3,76+3,76+3,83+3,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1363/60.png,https://cdn.sofifa.net/flags/se.png
4,167495,https://sofifa.com/player/167495/manuel-neuer/150002,M. Neuer,Manuel Peter Neuer,GK,90,90,63500000.0,300000.0,28,1986-03-27,193,92,21.0,FC Bayern München,German 1. Bundesliga,1.0,GK,1.0,NaN,2011-07-01,2019.0,21,Germany,1337.0,GK,1.0,Right,4,1,5,Medium/Medium,Normal (185+),Yes,NaN,NaN,"GK Up for Corners, GK Long Throw, 1-on-1 Rush",NaN,NaN,NaN,NaN,NaN,NaN,25,25,25,42,25,25,25,25,41,31,58,61,43,89,35,42,78,44,83,25,29,30,25,20,37,NaN,25,25,25,87,85,92,90,86,60.0,38+3,38+3,38+3,36+3,37+3,37+3,37+3,36+3,36+3,36+3,36+3,38+3,36+3,36+3,36+3,38+3,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1337/60.png,https://cdn.sofifa.net/flags/de.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,220806,https://sofifa.com/player/220806/ellis-redman/150002,E. Redman,Ellis Redman,CB,41,61,20000.0,2000.0,17,1996-09-26,187,81,112254.0,Newport County,English League Two,4.0,RES,35.0,NaN,2013-10-22,2015.0,50,Wales,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,66.0,25.0,29.0,30.0,39.0,53.0,25,25,41,36,25,25,21,25,33,26,65,66,52,36,55,22,62,56,52,25,50,41,25,22,31,NaN,38,40,35,12,6,15,8,6,NaN,32,32,32,33,30,30,30,33,30,30,30,34,32,32,32,34,37,38,38,38,37,40,41,41,41,40,10,https://cdn.sofifa.net/players/220/806/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16151,225509,https://sofifa.com/player/225509/aaron-collins/150002,A. Collins,Aaron Graham John Collins,ST,41,50,30000.0,2000.0,17,1997-06-01,178,57,112254.0,Newport County,English League Two,4.0,RES,39.0,NaN,2014-08-14,2015.0,50,Wales,NaN,NaN,NaN,Right,3,3,1,Medium/Medium,Lean (170-185),No,NaN,NaN,NaN,64.0,41.0,27.0,35.0,27.0,41.0,22,47,43,25,27,29,20,22,24,30,60,68,66,39,68,36,51,47,42,36,30,25,41,39,47,NaN,25,25,25,13,11,12,15,11,NaN,41,41,41,37,39,39,39,37,37,37,37,35,32,32,32,35,31,30,30,30,31,32,31,31,31,32,14,https://cdn.sofifa.net/players/225/509/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16152,201197,https://sofifa.com/player/201197/paul-tisdale/150002,P. Tisdale,Paul Tisdale,"CM, CAM",40,40,NaN,2000.0,41,1973-01-14,175,72,143.0,Exeter City,English League Two,4.0,RES,17.0,NaN,2006-06-26,2015.0,32,Malta,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,NaN,NaN,"Injury Prone, Playmaker (AI)",38.0,36.0,42.0,45.0,31.0,33.0,39,36,29,43,27,46,41,53,41,44,35,41,37,41,51,32,39,25,37,38,32,35,43,41,55,NaN,27,34,29,5,6,14,8,13,NaN,38,38,38,41-1,40,40,40,41-1,41-1,41-1,41-1,41-1,40,40,40,41-1,36,37,37,37,36,34,33,33,33,34,10,https://cdn.sofifa.net/players/201/197/15_120.png,https://cdn.sofifa.net/teams/143/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/mt.png
16153,217591,https://sofifa.com/player/217591/piotr-zemlo/150002,P. Żemło,Piotr Żemło,"LM, LB",40,50,15000.0,2000.0,18,1995-07-10,190,76,1873.0,Wisła Kraków,Polish T-Mobile Ekstraklasa,1.0,RES,43.0,NaN,2012-07-01,2015.0,37,Poland,NaN,NaN,NaN,Left,3,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,58.0,27.0,35.0,31.0,52.0,68.0,49,24,57,40,25,27,24,21,34,32,57,58,36,50,44,31,61,74,75,25,44,47,38,21,31,NaN,54,52,51,8,14,7,10,9,NaN,38,38,38,38,35,35,35,38,33,33,33,40,38,38,38,40,48,46,46,46,48,51-1,53-3,53-3,53-3,51-1,12,https://cdn.sofifa.net/players/217/591/15_120.png,https://cdn.sofifa.net/teams/1873/60.png,https://cdn.sofifa.net/flags/pl.png,NaN,https://cdn.sofifa.net/flags/pl.png
16154,222947,https://sofifa.com/player/222947/tom-davies/150002,T. Davies,Thomas Christopher Davies,CB,40,49,15000.0,2000.0,22,1992-04-18,180,70,112260.0,Fleetwood Town,English League One,3.0,RES,26.0,NaN,2014-03-11,2021.0,14,England,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (170-185),No,NaN,NaN,NaN,72.0,27.0,27.0,30.0,35.0,61.0,23,25,38,32,29,24,24,27,21,35,71,73,33,32,61,39,64,70,63,22,44,34,27,25,21,NaN,36,34,35,15,13,6,11,9,NaN,35,35,35,33,33,33,33,33,31,31,31,34,31,31,31,34,37,36,36,36,37,39,40,40,40,39,13,https://cdn.sofifa.net/players/222/947/15_120.png,https://cdn.sofifa.net/teams/112260/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-eng.png

In [8]:
df1.head()

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/150002,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,100500000.0,550000.0,27,1987-06-24,169,67,241.0,FC Barcelona,Spain Primera Division,1.0,CF,10.0,NaN,2004-07-01,2018.0,52,Argentina,1369.0,CF,10.0,Left,3,4,5,Medium/Low,Normal (170-),Yes,NaN,"#Speedster, #Dribbler, #FK Specialist, #Acrobat, #Clinical Finisher, #Complete Forward","Finesse Shot, Speed Dribbler (AI), One Club Player, Team Player",93.0,89.0,86.0,96.0,27.0,63.0,84,94,71,89,85,96,89,90,76,96,96,90,94,94,95,80,73,77,60,88,48,22,92,90,76,NaN,25,21,20,6,11,15,14,8,NaN,89+3,89+3,89+3,92+3,90+3,90+3,90+3,92+3,92+3,92+3,92+3,90+3,79+3,79+3,79+3,90+3,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png,https://cdn.sofifa.net/teams/241/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/150002,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,79000000.0,375000.0,29,1985-02-05,185,80,243.0,Real Madrid CF,Spain Primera Division,1.0,LW,7.0,NaN,2009-07-01,2018.0,38,Portugal,1354.0,LW,7.0,Right,4,5,5,High/Low,Normal (185+),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat, #Clinical Finisher, #Complete Forward","Power Free-Kick, Flair, Long Shot Taker (AI), Speed Dribbler (AI)",93.0,93.0,81.0,91.0,32.0,79.0,83,95,86,82,87,93,88,79,72,92,91,94,93,90,63,94,94,89,79,93,63,24,91,81,85,NaN,22,31,23,7,11,15,14,11,NaN,91+1,91+1,91+1,89+3,91+1,91+1,91+1,89+3,89+3,89+3,89+3,87+3,77+3,77+3,77+3,87+3,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png,https://cdn.sofifa.net/teams/243/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
2,9014,https://sofifa.com/player/9014/arjen-robben/150002,A. Robben,Arjen Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,1984-01-23,180,80,21.0,FC Bayern München,German 1. Bundesliga,1.0,SUB,10.0,NaN,2009-08-28,2017.0,34,Netherlands,105035.0,RS,11.0,Left,2,4,5,High/Low,Normal (170-185),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat","Diver, Injury Prone, Avoids Using Weaker Foot, Selfish, Long Shot Taker (AI), Speed Dribbler (AI), Chip Shot (AI)",93.0,86.0,83.0,92.0,32.0,64.0,80,85,50,86,86,93,85,83,76,90,93,93,93,89,91,86,61,78,65,90,47,39,89,84,80,NaN,29,26,26,10,8,11,5,15,NaN,84+3,84+3,84+3,88+2,87+3,87+3,87+3,88+2,88+2,88+2,88+2,87+3,78+3,78+3,78+3,87+3,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/105035/60.png,https://cdn.sofifa.net/flags/nl.png
3,41236,https://sofifa.com/player/41236/zlatan-ibrahimovic/150002,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,52500000.0,275000.0,32,1981-10-03,195,95,73.0,Paris Saint-Germain,French Ligue 1,1.0,ST,10.0,NaN,2012-07-01,2016.0,46,Sweden,1363.0,ST,10.0,Right,4,4,5,Medium/Low,Normal (185+),Yes,NaN,"#Poacher, #Aerial Threat, #Distance Shooter, #Acrobat, #Strength, #Clinical Finisher, #Complete Forward","Power Free-Kick, Leadership, Flair, Long Shot Taker (AI), Technical Dribbler (AI)",76.0,91.0,81.0,86.0,34.0,86.0,76,91,76,84,92,88,80,80,76,90,74,77,86,85,41,93,72,78,93,88,84,20,86,83,91,NaN,25,41,27,13,15,10,9,12,NaN,87+3,87+3,87+3,84+3,86+3,86+3,86+3,84+3,86+3,86+3,86+3,83+3,76+3,76+3,76+3,83+3,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1363/60.png,https://cdn.sofifa.net/flags/se.png
4,167495,https://sofifa.com/player/167495/manuel-neuer/150002,M. Neuer,Manuel Peter Neuer,GK,90,90,63500000.0,300000.0,28,1986-03-27,193,92,21.0,FC Bayern München,German 1. Bundesliga,1.0,GK,1.0,NaN,2011-07-01,2019.0,21,Germany,1337.0,GK,1.0,Right,4,1,5,Medium/Medium,Normal (185+),Yes,NaN,NaN,"GK Up for Corners, GK Long Throw, 1-on-1 Rush",NaN,NaN,NaN,NaN,NaN,NaN,25,25,25,42,25,25,25,25,41,31,58,61,43,89,35,42,78,44,83,25,29,30,25,20,37,NaN,25,25,25,87,85,92,90,86,60.0,38+3,38+3,38+3,36+3,37+3,37+3,37+3,36+3,36+3,36+3,36+3,38+3,36+3,36+3,36+3,38+3,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1337/60.png,https://cdn.sofifa.net/flags/de.png

In [9]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 16155 entries, 0 to 16154
Columns: 110 entries, sofifa_id to nation_flag_url
dtypes: float64(17), int64(43), str(50)
memory usage: 13.6 MB

In [10]:
df1.describe()

,sofifa_id,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,league_level,club_jersey_number,club_contract_valid_until,nationality_id,nation_team_id,nation_jersey_number,weak_foot,skill_moves,international_reputation,release_clause_eur,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
count,16155.000000,16155.000000,16155.000000,1.584400e+04,15916.000000,16155.000000,16155.000000,16155.000000,15916.000000,15916.000000,15916.000000,15916.000000,16155.000000,1081.000000,1081.000000,16155.000000,16155.000000,16155.000000,0.0,14380.000000,14380.000000,14380.000000,14380.000000,14380.000000,14380.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,0.0,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,1775.000000
mean,189298.540699,63.830393,68.350108,1.081706e+06,13252.513194,24.776230,181.083627,75.474342,39905.174353,1.378424,19.712868,2016.958469,51.686041,31611.000000,12.013876,2.929619,2.265429,1.122501,NaN,68.049026,51.582337,55.638665,60.525661,49.896662,64.537830,49.915877,45.892355,53.193377,56.907026,44.229403,54.527700,47.532343,44.354132,51.565583,57.607985,65.117858,65.585515,63.184958,60.646301,63.852553,55.978892,65.072609,63.417456,65.095574,48.329124,55.395543,46.879418,50.113278,50.765645,49.648344,NaN,45.009037,47.656639,45.885918,15.869514,15.511668,15.354875,15.504735,15.998514,43.865915
std,39762.547872,7.169896,6.580610,2.842704e+06,23608.922510,4.625321,6.618974,6.891796,52050.202038,0.736796,16.455708,2.071417,44.581841,48953.032671,6.660191,0.650281,0.717399,0.396263,NaN,10.965779,13.401158,10.725853,10.758680,15.788470,9.700209,15.772594,16.631994,14.759745,14.510707,15.304337,16.193951,16.105431,15.642168,14.867562,15.239856,13.689466,13.281079,14.271756,9.542055,13.389376,16.078853,11.620670,15.195508,12.616545,16.585339,16.814330,18.278554,16.395071,15.098199,14.552244,NaN,17.915206,18.743105,18.145497,17.576799,16.414173,16.010498,16.585081,17.983209,8.484421
min,2.000000,40.000000,40.000000,1.000000e+03,2000.000000,16.000000,155.000000,50.000000,1.000000,1.000000,1.000000,2014.000000,1.000000,974.000000,1.000000,1.000000,1.000000,1.000000,NaN,22.000000,22.000000,24.000000,25.000000,21.000000,28.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,21.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,NaN,20.000000,20.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,20.000000
25%,178042.500000,59.000000,64.000000,1.300000e+05,2000.000000,21.000000,176.000000,70.000000,379.000000,1.000000,8.000000,2015.000000,21.000000,1343.000000,6.000000,3.000000,2.000000,1.000000,NaN,62.000000,41.000000,49.000000,54.000000,33.000000,58.000000,37.000000,29.000000,45.000000,50.000000,30.000000,45.000000,34.000000,31.000000,41.000000,52.000000,56.500000,57.000000,56.000000,54.000000,56.000000,46.000000,58.000000,56.000000,58.000000,33.000000,43.000000,25.000000,37.000000,41.000000,39.000000,NaN,25.000000,25.000000,25.000000,8.000000,8.000000,8.000000,8.000000,8.000000,39.000000
50%,200844.000000,64.000000,68.000000,3.500000e+05,5000.000000,24.000000,181.000000,75.000000,1843.000000,1.000000,17.000000,2016.000000,42.000000,1365.000000,12.000000,3.000000,2.000000,1.000000,NaN,69.000000,53.000000,56.000000,62.000000,53.000000,65.000000,52.000000,47.000000,55.000000,60.000000,44.000000,58.000000,48.000000,42.000000,54.000000,61.000000,67.000000,68.000000,65.000000,61.000000,65.000000,59.000000,65.000000,66.000000,66.000000,51.000000,58.000000,50.000000,53.000000,52.000000,50.000000,NaN,46.000000,52.000000,49.000000,11.000000,11.000000,11.000000,10.000000,10.000000,44.000000
75%,214349.500000,68.000000,73.000000,8.250000e+05,10000.000000,28.000000,186.000000,80.000000,110398.000000,2.000000,26.000000,2019.000000,55.000000,110081.000000,18.000000,3.000000,3.000000,1.000000,NaN,75.000000,62.000000,63.000000,68.000000,63.000000,72.000000,62.000000,60.000000,64.000000,67.000000,57.000000,66.000000,60.000000,57.000000,63.000000,68.000000,75.000000,75.000000,74.000000,67.000000,73.000000,68.000000,73.000000,74.000000,74.000000,62.000000,68.000000,63.000000,63.000000,62.000000,61.000000,NaN,61.000000,64.000000,62.000000,13.000000,14.000000,13.000000,13.000000,13.000000,49.000000
max,254664.000000,93.000000,95.000000,1.005000e+08,550000.000000,44.000000,204.000000,110.000000,113147.000000,4.000000,99.000000,2021.000000,219.000000,111487.000000,28.000000,5.000000,5.000000,5.000000,NaN,97.000000,93.000000,91.000000,96.000000,90.000000,91.000000,91.000000,95.000000,94.000000,95.000000,92.000000,96.000000,94.000000,93.000000,95.000000,96.000000,97.000000,97.000000,96.000000,94.000000,97.000000,96.000000,97.000000,95.000000,97.000000,93.000000,95.000000,93.000000,94.000000,96.000000,95.000000,NaN,90.000000,91.000000,95.000000,88.000000,87.000000,92.000000,90.000000,90.000000,66.000000

In [11]:
df1.sample(10)

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
10253,169700,https://sofifa.com/player/169700/myles-weston/150002,M. Weston,Myles Arthur Eugene Wesley Weston,"LM, ST",61,62,250000.0,3000.0,26,1988-03-12,180,75,1954.0,Southend United,English League Two,4.0,ST,11.0,NaN,2014-06-14,2016.0,14,England,NaN,NaN,NaN,Left,3,3,1,Medium/Medium,Normal (170-185),No,NaN,#Speedster,Speed Dribbler (AI),93.0,58.0,54.0,62.0,29.0,58.0,59,59,35,55,54,61,44,56,54,55,92,93,80,49,83,57,54,71,59,58,41,40,53,49,55,NaN,22,28,20,11,12,10,15,13,NaN,57,57,57,62,58,58,58,62,57,57,57,61,52,52,52,61,48,46,46,46,48,43,36,36,36,43,15,https://cdn.sofifa.net/players/169/700/15_120.png,https://cdn.sofifa.net/teams/1954/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-eng.png
4711,242330,https://sofifa.com/player/242330/ariel-nunez/150002,A. Núñez,José Ariel Núñez Portelli,"CAM, CF",68,74,1200000.0,15000.0,25,1988-09-12,172,71,269.0,Brøndby IF,Danish Superliga,1.0,SUB,10.0,NaN,2014-01-31,2018.0,58,Paraguay,NaN,NaN,NaN,Right,4,3,1,High/Low,Normal (170-185),No,NaN,NaN,Beat Offside Trap,78.0,73.0,57.0,69.0,28.0,54.0,53,75,70,64,71,64,56,64,48,71,79,78,84,64,79,73,82,63,58,66,25,21,82,55,76,NaN,22,27,25,7,13,11,10,5,NaN,72,72,72,68,70,70,70,68,68,68,68,65,57,57,57,65,49,46,46,46,49,44,41,41,41,44,12,https://cdn.sofifa.net/players/242/330/15_120.png,https://cdn.sofifa.net/teams/269/60.png,https://cdn.sofifa.net/flags/dk.png,NaN,https://cdn.sofifa.net/flags/py.png
3919,218667,https://sofifa.com/player/218667/bernardo-mota-carvalho-e-silva/150002,Bernardo Silva,Bernardo Mota Veiga de Carvalho e Silva,CAM,69,81,850000.0,8000.0,19,1994-08-10,170,65,69.0,AS Monaco,French Ligue 1,1.0,SUB,15.0,SL Benfica,NaN,2015.0,38,Portugal,NaN,NaN,NaN,Left,3,4,1,High/Medium,Lean (170-),No,NaN,NaN,"Flair, Playmaker (AI), Technical Dribbler (AI)",82.0,58.0,62.0,76.0,33.0,48.0,48,54,50,66,64,75,73,54,61,72,86,78,85,76,82,62,53,65,36,57,57,39,66,68,63,NaN,27,33,26,8,9,13,11,8,NaN,64,64,64,68,66,66,66,68,69,69,69,68,63,63,63,68,53,54,54,54,53,49,42,42,42,49,13,https://cdn.sofifa.net/players/218/667/15_120.png,https://cdn.sofifa.net/teams/69/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/pt.png
2327,213516,https://sofifa.com/player/213516/ricardo-jorge-da-luz-horta/150002,Ricardo Horta,Ricardo Jorge da Luz Horta,"LW, RW, LM",72,80,2000000.0,20000.0,19,1994-09-15,173,61,573.0,Málaga CF,Spain Primera Division,1.0,LM,10.0,NaN,2014-07-12,2019.0,38,Portugal,1354.0,SUB,11.0,Right,3,3,1,Medium/Medium,Lean (170-185),No,NaN,NaN,"Finesse Shot, Technical Dribbler (AI)",78.0,67.0,66.0,77.0,28.0,53.0,64,71,50,70,51,78,77,50,62,75,78,78,78,72,74,70,62,69,49,58,40,30,72,64,70,NaN,23,27,24,6,8,9,7,12,NaN,68,68,68,72,70,70,70,72,71,71,71,71,63,63,63,71,54,52,52,52,54,47,40,40,40,47,12,https://cdn.sofifa.net/players/213/516/15_120.png,https://cdn.sofifa.net/teams/573/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
9593,192279,https://sofifa.com/player/192279/igor-shitov/150002,I. Shitov,Igor Shitov,RB,62,65,300000.0,3000.0,27,1986-10-24,185,80,110106.0,FC Mordovia Saransk,Russian Premier League,1.0,SUB,4.0,NaN,2014-01-28,2016.0,6,Belarus,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,54.0,40.0,56.0,42.0,64.0,78.0,63,21,62,56,23,32,34,35,61,50,53,55,55,56,56,68,72,75,82,66,72,60,31,55,29,NaN,64,65,66,11,6,12,9,15,NaN,45,45,45,49,48,48,48,49,49,49,49,52,54,54,54,52,59,62,62,62,59,62,65,65,65,62,13,https://cdn.sofifa.net/players/192/279/15_120.png,https://cdn.sofifa.net/teams/110106/60.png,https://cdn.sofifa.net/flags/ru.png,NaN,https://cdn.sofifa.net/flags/by.png
13107,225012,https://sofifa.com/player/225012/segun-owobowale/150002,S. Owobowale,Oluwasegun Owobowale,LW,58,77,100000.0,2000.0,17,1997-03-22,180,70,650.0,ADO Den Haag,Holland Eredivisie,1.0,SUB,30.0,NaN,2014-01-01,2021.0,34,Netherlands,NaN,NaN,NaN,Left,3,3,1,Medium/Medium,Lean (170-185),No,NaN,NaN,NaN,84.0,56.0,50.0,62.0,32.0,44.0,52,61,45,50,51,58,49,48,46,67,85,83,78,40,68,65,41,48,48,40,28,25,47,50,62,NaN,29,35,32,14,9,13,12,11,NaN,56,56,56,58,56,56,56,58,55,55,55,56,47,47,47,56,46,42,42,42,46,41,37,37,37,41,13,https://cdn.sofifa.net/players/225/012/15_120.png,https://cdn.sofifa.net/teams/650/60.png,https://cdn.sofifa.net/flags/nl.png,NaN,https://cdn.sofifa.net/flags/nl.png
3222,203671,https://sofifa.com/player/203671/juan-ignacio-gomez/150002,J. Gomez,Juan Ignacio Gómez Taleb,"LW, RW",70,70,1500000.0,20000.0,29,1985-05-20,180,75,206.0,Hellas Verona,Italian Serie A,1.0,RW,21.0,NaN,2008-07-01,2015.0,52,Argentina,NaN,NaN,NaN,Right,3,3,1,Medium/Low,Lean (170-185),No,NaN,NaN,NaN,85.0,65.0,60.0,76.0,33.0,68.0,61,67,67,62,67,76,67,61,48,76,83,86,79,68,77,71,85,77,69,51,49,28,71,63,72,NaN,21,39,24,7,13,5,5,13,NaN,70,70,70,70,69,69,69,70,69,69,69,69,60,60,60,69,54,52,52,52,54,50,46,46,46,50,13,https://cdn.sofifa.net/players/203/671/15_120.png,https://cdn.sofifa.net/teams/206/60.png,https://cdn.sofifa.net/flags/it.png,NaN,https://cdn.sofifa.net/flags/ar.png
13065,224198,https://sofifa.com/player/224198/karim-hafez/150002,K. Hafez,Karim Hafez Ramadan,LB,58,69,90000.0,2000.0,18,1996-03-12,175,70,239.0,Lierse SK,Belgian Jupiler Pro League,1.0,SUB,33.0,NaN,2014-07-01,2015.0,111,Egypt,NaN,NaN,NaN,Left,2,2,1,Medium/Medium,Normal (170-185),No,NaN,NaN,NaN,68.0,26.0,48.0,58.0,59.0,53.0,59,23,56,54,21,53,46,38,43,62,69,68,66,55,76,24,57,55,51,28,55,56,49,32,37,NaN,63,60,57,6,12,15,10,6,NaN,43,43,43,54,45,45,45,54,47,47,47,54,50,50,50,54,58,54,54,54,58,58,57,57,57,58,12,https://cdn.sofifa.net/players/224/198/15_120.png,https://cdn.sofifa.net/teams/239/60.png,https://cdn.sofifa.net/flags/be.png,NaN,https://cdn.sofifa.net/flags/eg.png
11201,194679,https://sofifa.com/player/194679/mark-halstead/150002,M. Halstead,Mark James Halstead,GK,60,64,210000.0,2000.0,24,1990-01-17,191,89,127.0,Shrewsbury Town,English League Two,4.0,SUB,21.0,NaN,2014-06-06,2016.0,14,England,NaN,NaN,NaN,Right,2,1,1,Medium/Medium,Lean (185+),No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,25,25,22,25,25,25,25,31,22,51,47,26,51,33,25,66,25,67,25,35,21,25,25,25,NaN,25,25,25,61,58,55,59,64,49.0,31,31,31,29,29,29,29,29,27,27,27,29,27,27,27,29,27,30,30,30,27,28,32,32,32,28,60,https://cdn.sofifa.net/players/194/679/15_120.png,https://cdn.sofifa.net/teams/127/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-eng.png
10245,166764,https://sofifa.com/player/166764/trevor-carson/150002,T. Carson,Trevor Carson,GK,61,62,230000.0,3000.0,26,1988-03-05,183,80,1936.0,Cheltenham Town,English League Two,4.0,GK,1.0,NaN,2014-07-01,2016.0,35,Northern Ireland,NaN,NaN,NaN,Right,3,1,1,Medium/Medium,Normal (170-185),No,NaN,NaN,GK Up for Corners,NaN,NaN,NaN,NaN,NaN,NaN,25,25,25,25,25,25,25,25,25,25,58,40,56,55,67,27,65,43,62,25,36,25,25,25,22,NaN,25,25,25,63,55,64,61,67,48.0,32,32,32,31,30,30,30,31,30,30,30,31,28,28,28,31,30,32,32,32,30,30,33,33,33,30,61,https://cdn.sofifa.net/players/166/764/15_120.png,https://cdn.sofifa.net/teams/1936/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-nir.png

In [12]:
df1["sofifa_id"].isnull().sum

<bound method Series.sum of 0        False
1        False
2        False
3        False
4        False
         ...
16150    False
16151    False
16152    False
16153    False
16154    False
Name: sofifa_id, Length: 16155, dtype: bool>

In [13]:
df1[df1["overall"].isnull()]

Empty DataFrame
Columns: [sofifa_id, player_url, short_name, long_name, player_positions, overall, potential, value_eur, wage_eur, age, dob, height_cm, weight_kg, club_team_id, club_name, league_name, league_level, club_position, club_jersey_number, club_loaned_from, club_joined, club_contract_valid_until, nationality_id, nationality_name, nation_team_id, nation_position, nation_jersey_number, preferred_foot, weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, release_clause_eur, player_tags, player_traits, pace, shooting, passing, dribbling, defending, physic, attacking_crossing, attacking_finishing, attacking_heading_accuracy, attacking_short_passing, attacking_volleys, skill_dribbling, skill_curve, skill_fk_accuracy, skill_long_passing, skill_ball_control, movement_acceleration, movement_sprint_speed, movement_agility, movement_reactions, movement_balance, power_shot_power, power_jumping, power_stamina, power_strength, power_long_shots, mentality_aggression, mentality_interceptions, mentality_positioning, mentality_vision, mentality_penalties, mentality_composure, defending_marking_awareness, defending_standing_tackle, defending_sliding_tackle, goalkeeping_diving, goalkeeping_handling, goalkeeping_kicking, goalkeeping_positioning, goalkeeping_reflexes, goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, ...]
Index: []

In [14]:
df1.duplicated(subset=["short_name","long_name"]).value_counts()

False    16129
True        26
Name: count, dtype: int64

In [15]:
df1["age"].sort_values()

14371    16
16118    16
16107    16
15435    16
15779    16
         ..
405      43
16143    44
10365    44
15839    44
3403     44
Name: age, Length: 16155, dtype: int64

In [16]:
df1.describe()

,sofifa_id,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,league_level,club_jersey_number,club_contract_valid_until,nationality_id,nation_team_id,nation_jersey_number,weak_foot,skill_moves,international_reputation,release_clause_eur,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
count,16155.000000,16155.000000,16155.000000,1.584400e+04,15916.000000,16155.000000,16155.000000,16155.000000,15916.000000,15916.000000,15916.000000,15916.000000,16155.000000,1081.000000,1081.000000,16155.000000,16155.000000,16155.000000,0.0,14380.000000,14380.000000,14380.000000,14380.000000,14380.000000,14380.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,0.0,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,1775.000000
mean,189298.540699,63.830393,68.350108,1.081706e+06,13252.513194,24.776230,181.083627,75.474342,39905.174353,1.378424,19.712868,2016.958469,51.686041,31611.000000,12.013876,2.929619,2.265429,1.122501,NaN,68.049026,51.582337,55.638665,60.525661,49.896662,64.537830,49.915877,45.892355,53.193377,56.907026,44.229403,54.527700,47.532343,44.354132,51.565583,57.607985,65.117858,65.585515,63.184958,60.646301,63.852553,55.978892,65.072609,63.417456,65.095574,48.329124,55.395543,46.879418,50.113278,50.765645,49.648344,NaN,45.009037,47.656639,45.885918,15.869514,15.511668,15.354875,15.504735,15.998514,43.865915
std,39762.547872,7.169896,6.580610,2.842704e+06,23608.922510,4.625321,6.618974,6.891796,52050.202038,0.736796,16.455708,2.071417,44.581841,48953.032671,6.660191,0.650281,0.717399,0.396263,NaN,10.965779,13.401158,10.725853,10.758680,15.788470,9.700209,15.772594,16.631994,14.759745,14.510707,15.304337,16.193951,16.105431,15.642168,14.867562,15.239856,13.689466,13.281079,14.271756,9.542055,13.389376,16.078853,11.620670,15.195508,12.616545,16.585339,16.814330,18.278554,16.395071,15.098199,14.552244,NaN,17.915206,18.743105,18.145497,17.576799,16.414173,16.010498,16.585081,17.983209,8.484421
min,2.000000,40.000000,40.000000,1.000000e+03,2000.000000,16.000000,155.000000,50.000000,1.000000,1.000000,1.000000,2014.000000,1.000000,974.000000,1.000000,1.000000,1.000000,1.000000,NaN,22.000000,22.000000,24.000000,25.000000,21.000000,28.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,21.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,NaN,20.000000,20.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,20.000000
25%,178042.500000,59.000000,64.000000,1.300000e+05,2000.000000,21.000000,176.000000,70.000000,379.000000,1.000000,8.000000,2015.000000,21.000000,1343.000000,6.000000,3.000000,2.000000,1.000000,NaN,62.000000,41.000000,49.000000,54.000000,33.000000,58.000000,37.000000,29.000000,45.000000,50.000000,30.000000,45.000000,34.000000,31.000000,41.000000,52.000000,56.500000,57.000000,56.000000,54.000000,56.000000,46.000000,58.000000,56.000000,58.000000,33.000000,43.000000,25.000000,37.000000,41.000000,39.000000,NaN,25.000000,25.000000,25.000000,8.000000,8.000000,8.000000,8.000000,8.000000,39.000000
50%,200844.000000,64.000000,68.000000,3.500000e+05,5000.000000,24.000000,181.000000,75.000000,1843.000000,1.000000,17.000000,2016.000000,42.000000,1365.000000,12.000000,3.000000,2.000000,1.000000,NaN,69.000000,53.000000,56.000000,62.000000,53.000000,65.000000,52.000000,47.000000,55.000000,60.000000,44.000000,58.000000,48.000000,42.000000,54.000000,61.000000,67.000000,68.000000,65.000000,61.000000,65.000000,59.000000,65.000000,66.000000,66.000000,51.000000,58.000000,50.000000,53.000000,52.000000,50.000000,NaN,46.000000,52.000000,49.000000,11.000000,11.000000,11.000000,10.000000,10.000000,44.000000
75%,214349.500000,68.000000,73.000000,8.250000e+05,10000.000000,28.000000,186.000000,80.000000,110398.000000,2.000000,26.000000,2019.000000,55.000000,110081.000000,18.000000,3.000000,3.000000,1.000000,NaN,75.000000,62.000000,63.000000,68.000000,63.000000,72.000000,62.000000,60.000000,64.000000,67.000000,57.000000,66.000000,60.000000,57.000000,63.000000,68.000000,75.000000,75.000000,74.000000,67.000000,73.000000,68.000000,73.000000,74.000000,74.000000,62.000000,68.000000,63.000000,63.000000,62.000000,61.000000,NaN,61.000000,64.000000,62.000000,13.000000,14.000000,13.000000,13.000000,13.000000,49.000000
max,254664.000000,93.000000,95.000000,1.005000e+08,550000.000000,44.000000,204.000000,110.000000,113147.000000,4.000000,99.000000,2021.000000,219.000000,111487.000000,28.000000,5.000000,5.000000,5.000000,NaN,97.000000,93.000000,91.000000,96.000000,90.000000,91.000000,91.000000,95.000000,94.000000,95.000000,92.000000,96.000000,94.000000,93.000000,95.000000,96.000000,97.000000,97.000000,96.000000,94.000000,97.000000,96.000000,97.000000,95.000000,97.000000,93.000000,95.000000,93.000000,94.000000,96.000000,95.000000,NaN,90.000000,91.000000,95.000000,88.000000,87.000000,92.000000,90.000000,90.000000,66.000000

In [17]:
df1

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/150002,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,100500000.0,550000.0,27,1987-06-24,169,67,241.0,FC Barcelona,Spain Primera Division,1.0,CF,10.0,NaN,2004-07-01,2018.0,52,Argentina,1369.0,CF,10.0,Left,3,4,5,Medium/Low,Normal (170-),Yes,NaN,"#Speedster, #Dribbler, #FK Specialist, #Acrobat, #Clinical Finisher, #Complete Forward","Finesse Shot, Speed Dribbler (AI), One Club Player, Team Player",93.0,89.0,86.0,96.0,27.0,63.0,84,94,71,89,85,96,89,90,76,96,96,90,94,94,95,80,73,77,60,88,48,22,92,90,76,NaN,25,21,20,6,11,15,14,8,NaN,89+3,89+3,89+3,92+3,90+3,90+3,90+3,92+3,92+3,92+3,92+3,90+3,79+3,79+3,79+3,90+3,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png,https://cdn.sofifa.net/teams/241/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/150002,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,79000000.0,375000.0,29,1985-02-05,185,80,243.0,Real Madrid CF,Spain Primera Division,1.0,LW,7.0,NaN,2009-07-01,2018.0,38,Portugal,1354.0,LW,7.0,Right,4,5,5,High/Low,Normal (185+),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat, #Clinical Finisher, #Complete Forward","Power Free-Kick, Flair, Long Shot Taker (AI), Speed Dribbler (AI)",93.0,93.0,81.0,91.0,32.0,79.0,83,95,86,82,87,93,88,79,72,92,91,94,93,90,63,94,94,89,79,93,63,24,91,81,85,NaN,22,31,23,7,11,15,14,11,NaN,91+1,91+1,91+1,89+3,91+1,91+1,91+1,89+3,89+3,89+3,89+3,87+3,77+3,77+3,77+3,87+3,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png,https://cdn.sofifa.net/teams/243/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
2,9014,https://sofifa.com/player/9014/arjen-robben/150002,A. Robben,Arjen Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,1984-01-23,180,80,21.0,FC Bayern München,German 1. Bundesliga,1.0,SUB,10.0,NaN,2009-08-28,2017.0,34,Netherlands,105035.0,RS,11.0,Left,2,4,5,High/Low,Normal (170-185),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat","Diver, Injury Prone, Avoids Using Weaker Foot, Selfish, Long Shot Taker (AI), Speed Dribbler (AI), Chip Shot (AI)",93.0,86.0,83.0,92.0,32.0,64.0,80,85,50,86,86,93,85,83,76,90,93,93,93,89,91,86,61,78,65,90,47,39,89,84,80,NaN,29,26,26,10,8,11,5,15,NaN,84+3,84+3,84+3,88+2,87+3,87+3,87+3,88+2,88+2,88+2,88+2,87+3,78+3,78+3,78+3,87+3,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/105035/60.png,https://cdn.sofifa.net/flags/nl.png
3,41236,https://sofifa.com/player/41236/zlatan-ibrahimovic/150002,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,52500000.0,275000.0,32,1981-10-03,195,95,73.0,Paris Saint-Germain,French Ligue 1,1.0,ST,10.0,NaN,2012-07-01,2016.0,46,Sweden,1363.0,ST,10.0,Right,4,4,5,Medium/Low,Normal (185+),Yes,NaN,"#Poacher, #Aerial Threat, #Distance Shooter, #Acrobat, #Strength, #Clinical Finisher, #Complete Forward","Power Free-Kick, Leadership, Flair, Long Shot Taker (AI), Technical Dribbler (AI)",76.0,91.0,81.0,86.0,34.0,86.0,76,91,76,84,92,88,80,80,76,90,74,77,86,85,41,93,72,78,93,88,84,20,86,83,91,NaN,25,41,27,13,15,10,9,12,NaN,87+3,87+3,87+3,84+3,86+3,86+3,86+3,84+3,86+3,86+3,86+3,83+3,76+3,76+3,76+3,83+3,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1363/60.png,https://cdn.sofifa.net/flags/se.png
4,167495,https://sofifa.com/player/167495/manuel-neuer/150002,M. Neuer,Manuel Peter Neuer,GK,90,90,63500000.0,300000.0,28,1986-03-27,193,92,21.0,FC Bayern München,German 1. Bundesliga,1.0,GK,1.0,NaN,2011-07-01,2019.0,21,Germany,1337.0,GK,1.0,Right,4,1,5,Medium/Medium,Normal (185+),Yes,NaN,NaN,"GK Up for Corners, GK Long Throw, 1-on-1 Rush",NaN,NaN,NaN,NaN,NaN,NaN,25,25,25,42,25,25,25,25,41,31,58,61,43,89,35,42,78,44,83,25,29,30,25,20,37,NaN,25,25,25,87,85,92,90,86,60.0,38+3,38+3,38+3,36+3,37+3,37+3,37+3,36+3,36+3,36+3,36+3,38+3,36+3,36+3,36+3,38+3,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1337/60.png,https://cdn.sofifa.net/flags/de.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,220806,https://sofifa.com/player/220806/ellis-redman/150002,E. Redman,Ellis Redman,CB,41,61,20000.0,2000.0,17,1996-09-26,187,81,112254.0,Newport County,English League Two,4.0,RES,35.0,NaN,2013-10-22,2015.0,50,Wales,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,66.0,25.0,29.0,30.0,39.0,53.0,25,25,41,36,25,25,21,25,33,26,65,66,52,36,55,22,62,56,52,25,50,41,25,22,31,NaN,38,40,35,12,6,15,8,6,NaN,32,32,32,33,30,30,30,33,30,30,30,34,32,32,32,34,37,38,38,38,37,40,41,41,41,40,10,https://cdn.sofifa.net/players/220/806/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16151,225509,https://sofifa.com/player/225509/aaron-collins/150002,A. Collins,Aaron Graham John Collins,ST,41,50,30000.0,2000.0,17,1997-06-01,178,57,112254.0,Newport County,English League Two,4.0,RES,39.0,NaN,2014-08-14,2015.0,50,Wales,NaN,NaN,NaN,Right,3,3,1,Medium/Medium,Lean (170-185),No,NaN,NaN,NaN,64.0,41.0,27.0,35.0,27.0,41.0,22,47,43,25,27,29,20,22,24,30,60,68,66,39,68,36,51,47,42,36,30,25,41,39,47,NaN,25,25,25,13,11,12,15,11,NaN,41,41,41,37,39,39,39,37,37,37,37,35,32,32,32,35,31,30,30,30,31,32,31,31,31,32,14,https://cdn.sofifa.net/players/225/509/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16152,201197,https://sofifa.com/player/201197/paul-tisdale/150002,P. Tisdale,Paul Tisdale,"CM, CAM",40,40,NaN,2000.0,41,1973-01-14,175,72,143.0,Exeter City,English League Two,4.0,RES,17.0,NaN,2006-06-26,2015.0,32,Malta,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,NaN,NaN,"Injury Prone, Playmaker (AI)",38.0,36.0,42.0,45.0,31.0,33.0,39,36,29,43,27,46,41,53,41,44,35,41,37,41,51,32,39,25,37,38,32,35,43,41,55,NaN,27,34,29,5,6,14,8,13,NaN,38,38,38,41-1,40,40,40,41-1,41-1,41-1,41-1,41-1,40,40,40,41-1,36,37,37,37,36,34,33,33,33,34,10,https://cdn.sofifa.net/players/201/197/15_120.png,https://cdn.sofifa.net/teams/143/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/mt.png
16153,217591,https://sofifa.com/player/217591/piotr-zemlo/150002,P. Żemło,Piotr Żemło,"LM, LB",40,50,15000.0,2000.0,18,1995-07-10,190,76,1873.0,Wisła Kraków,Polish T-Mobile Ekstraklasa,1.0,RES,43.0,NaN,2012-07-01,2015.0,37,Poland,NaN,NaN,NaN,Left,3,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,58.0,27.0,35.0,31.0,52.0,68.0,49,24,57,40,25,27,24,21,34,32,57,58,36,50,44,31,61,74,75,25,44,47,38,21,31,NaN,54,52,51,8,14,7,10,9,NaN,38,38,38,38,35,35,35,38,33,33,33,40,38,38,38,40,48,46,46,46,48,51-1,53-3,53-3,53-3,51-1,12,https://cdn.sofifa.net/players/217/591/15_120.png,https://cdn.sofifa.net/teams/1873/60.png,https://cdn.sofifa.net/flags/pl.png,NaN,https://cdn.sofifa.net/flags/pl.png
16154,222947,https://sofifa.com/player/222947/tom-davies/150002,T. Davies,Thomas Christopher Davies,CB,40,49,15000.0,2000.0,22,1992-04-18,180,70,112260.0,Fleetwood Town,English League One,3.0,RES,26.0,NaN,2014-03-11,2021.0,14,England,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (170-185),No,NaN,NaN,NaN,72.0,27.0,27.0,30.0,35.0,61.0,23,25,38,32,29,24,24,27,21,35,71,73,33,32,61,39,64,70,63,22,44,34,27,25,21,NaN,36,34,35,15,13,6,11,9,NaN,35,35,35,33,33,33,33,33,31,31,31,34,31,31,31,34,37,36,36,36,37,39,40,40,40,39,13,https://cdn.sofifa.net/players/222/947/15_120.png,https://cdn.sofifa.net/teams/112260/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-eng.png

In [18]:
df1 = df1.rename(index = {"2_" :"2"})

In [23]:
df1 = df1.rename(columns = str.lower)
df1

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/150002,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,100500000.0,550000.0,27,1987-06-24,169,67,241.0,FC Barcelona,Spain Primera Division,1.0,CF,10.0,NaN,2004-07-01,2018.0,52,Argentina,1369.0,CF,10.0,Left,3,4,5,Medium/Low,Normal (170-),Yes,NaN,"#Speedster, #Dribbler, #FK Specialist, #Acrobat, #Clinical Finisher, #Complete Forward","Finesse Shot, Speed Dribbler (AI), One Club Player, Team Player",93.0,89.0,86.0,96.0,27.0,63.0,84,94,71,89,85,96,89,90,76,96,96,90,94,94,95,80,73,77,60,88,48,22,92,90,76,NaN,25,21,20,6,11,15,14,8,NaN,89+3,89+3,89+3,92+3,90+3,90+3,90+3,92+3,92+3,92+3,92+3,90+3,79+3,79+3,79+3,90+3,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png,https://cdn.sofifa.net/teams/241/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/150002,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,79000000.0,375000.0,29,1985-02-05,185,80,243.0,Real Madrid CF,Spain Primera Division,1.0,LW,7.0,NaN,2009-07-01,2018.0,38,Portugal,1354.0,LW,7.0,Right,4,5,5,High/Low,Normal (185+),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat, #Clinical Finisher, #Complete Forward","Power Free-Kick, Flair, Long Shot Taker (AI), Speed Dribbler (AI)",93.0,93.0,81.0,91.0,32.0,79.0,83,95,86,82,87,93,88,79,72,92,91,94,93,90,63,94,94,89,79,93,63,24,91,81,85,NaN,22,31,23,7,11,15,14,11,NaN,91+1,91+1,91+1,89+3,91+1,91+1,91+1,89+3,89+3,89+3,89+3,87+3,77+3,77+3,77+3,87+3,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png,https://cdn.sofifa.net/teams/243/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
2,9014,https://sofifa.com/player/9014/arjen-robben/150002,A. Robben,Arjen Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,1984-01-23,180,80,21.0,FC Bayern München,German 1. Bundesliga,1.0,SUB,10.0,NaN,2009-08-28,2017.0,34,Netherlands,105035.0,RS,11.0,Left,2,4,5,High/Low,Normal (170-185),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat","Diver, Injury Prone, Avoids Using Weaker Foot, Selfish, Long Shot Taker (AI), Speed Dribbler (AI), Chip Shot (AI)",93.0,86.0,83.0,92.0,32.0,64.0,80,85,50,86,86,93,85,83,76,90,93,93,93,89,91,86,61,78,65,90,47,39,89,84,80,NaN,29,26,26,10,8,11,5,15,NaN,84+3,84+3,84+3,88+2,87+3,87+3,87+3,88+2,88+2,88+2,88+2,87+3,78+3,78+3,78+3,87+3,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/105035/60.png,https://cdn.sofifa.net/flags/nl.png
3,41236,https://sofifa.com/player/41236/zlatan-ibrahimovic/150002,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,52500000.0,275000.0,32,1981-10-03,195,95,73.0,Paris Saint-Germain,French Ligue 1,1.0,ST,10.0,NaN,2012-07-01,2016.0,46,Sweden,1363.0,ST,10.0,Right,4,4,5,Medium/Low,Normal (185+),Yes,NaN,"#Poacher, #Aerial Threat, #Distance Shooter, #Acrobat, #Strength, #Clinical Finisher, #Complete Forward","Power Free-Kick, Leadership, Flair, Long Shot Taker (AI), Technical Dribbler (AI)",76.0,91.0,81.0,86.0,34.0,86.0,76,91,76,84,92,88,80,80,76,90,74,77,86,85,41,93,72,78,93,88,84,20,86,83,91,NaN,25,41,27,13,15,10,9,12,NaN,87+3,87+3,87+3,84+3,86+3,86+3,86+3,84+3,86+3,86+3,86+3,83+3,76+3,76+3,76+3,83+3,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1363/60.png,https://cdn.sofifa.net/flags/se.png
4,167495,https://sofifa.com/player/167495/manuel-neuer/150002,M. Neuer,Manuel Peter Neuer,GK,90,90,63500000.0,300000.0,28,1986-03-27,193,92,21.0,FC Bayern München,German 1. Bundesliga,1.0,GK,1.0,NaN,2011-07-01,2019.0,21,Germany,1337.0,GK,1.0,Right,4,1,5,Medium/Medium,Normal (185+),Yes,NaN,NaN,"GK Up for Corners, GK Long Throw, 1-on-1 Rush",NaN,NaN,NaN,NaN,NaN,NaN,25,25,25,42,25,25,25,25,41,31,58,61,43,89,35,42,78,44,83,25,29,30,25,20,37,NaN,25,25,25,87,85,92,90,86,60.0,38+3,38+3,38+3,36+3,37+3,37+3,37+3,36+3,36+3,36+3,36+3,38+3,36+3,36+3,36+3,38+3,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1337/60.png,https://cdn.sofifa.net/flags/de.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,220806,https://sofifa.com/player/220806/ellis-redman/150002,E. Redman,Ellis Redman,CB,41,61,20000.0,2000.0,17,1996-09-26,187,81,112254.0,Newport County,English League Two,4.0,RES,35.0,NaN,2013-10-22,2015.0,50,Wales,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,66.0,25.0,29.0,30.0,39.0,53.0,25,25,41,36,25,25,21,25,33,26,65,66,52,36,55,22,62,56,52,25,50,41,25,22,31,NaN,38,40,35,12,6,15,8,6,NaN,32,32,32,33,30,30,30,33,30,30,30,34,32,32,32,34,37,38,38,38,37,40,41,41,41,40,10,https://cdn.sofifa.net/players/220/806/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16151,225509,https://sofifa.com/player/225509/aaron-collins/150002,A. Collins,Aaron Graham John Collins,ST,41,50,30000.0,2000.0,17,1997-06-01,178,57,112254.0,Newport County,English League Two,4.0,RES,39.0,NaN,2014-08-14,2015.0,50,Wales,NaN,NaN,NaN,Right,3,3,1,Medium/Medium,Lean (170-185),No,NaN,NaN,NaN,64.0,41.0,27.0,35.0,27.0,41.0,22,47,43,25,27,29,20,22,24,30,60,68,66,39,68,36,51,47,42,36,30,25,41,39,47,NaN,25,25,25,13,11,12,15,11,NaN,41,41,41,37,39,39,39,37,37,37,37,35,32,32,32,35,31,30,30,30,31,32,31,31,31,32,14,https://cdn.sofifa.net/players/225/509/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16152,201197,https://sofifa.com/player/201197/paul-tisdale/150002,P. Tisdale,Paul Tisdale,"CM, CAM",40,40,NaN,2000.0,41,1973-01-14,175,72,143.0,Exeter City,English League Two,4.0,RES,17.0,NaN,2006-06-26,2015.0,32,Malta,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,NaN,NaN,"Injury Prone, Playmaker (AI)",38.0,36.0,42.0,45.0,31.0,33.0,39,36,29,43,27,46,41,53,41,44,35,41,37,41,51,32,39,25,37,38,32,35,43,41,55,NaN,27,34,29,5,6,14,8,13,NaN,38,38,38,41-1,40,40,40,41-1,41-1,41-1,41-1,41-1,40,40,40,41-1,36,37,37,37,36,34,33,33,33,34,10,https://cdn.sofifa.net/players/201/197/15_120.png,https://cdn.sofifa.net/teams/143/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/mt.png
16153,217591,https://sofifa.com/player/217591/piotr-zemlo/150002,P. Żemło,Piotr Żemło,"LM, LB",40,50,15000.0,2000.0,18,1995-07-10,190,76,1873.0,Wisła Kraków,Polish T-Mobile Ekstraklasa,1.0,RES,43.0,NaN,2012-07-01,2015.0,37,Poland,NaN,NaN,NaN,Left,3,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,58.0,27.0,35.0,31.0,52.0,68.0,49,24,57,40,25,27,24,21,34,32,57,58,36,50,44,31,61,74,75,25,44,47,38,21,31,NaN,54,52,51,8,14,7,10,9,NaN,38,38,38,38,35,35,35,38,33,33,33,40,38,38,38,40,48,46,46,46,48,51-1,53-3,53-3,53-3,51-1,12,https://cdn.sofifa.net/players/217/591/15_120.png,https://cdn.sofifa.net/teams/1873/60.png,https://cdn.sofifa.net/flags/pl.png,NaN,https://cdn.sofifa.net/flags/pl.png
16154,222947,https://sofifa.com/player/222947/tom-davies/150002,T. Davies,Thomas Christopher Davies,CB,40,49,15000.0,2000.0,22,1992-04-18,180,70,112260.0,Fleetwood Town,English League One,3.0,RES,26.0,NaN,2014-03-11,2021.0,14,England,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (170-185),No,NaN,NaN,NaN,72.0,27.0,27.0,30.0,35.0,61.0,23,25,38,32,29,24,24,27,21,35,71,73,33,32,61,39,64,70,63,22,44,34,27,25,21,NaN,36,34,35,15,13,6,11,9,NaN,35,35,35,33,33,33,33,33,31,31,31,34,31,31,31,34,37,36,36,36,37,39,40,40,40,39,13,https://cdn.sofifa.net/players/222/947/15_120.png,https://cdn.sofifa.net/teams/112260/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-eng.png

In [25]:
df1.set_index("short_name")

,sofifa_id,player_url,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
short_name,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/150002,Lionel Andrés Messi Cuccittini,CF,93,95,100500000.0,550000.0,27,1987-06-24,169,67,241.0,FC Barcelona,Spain Primera Division,1.0,CF,10.0,NaN,2004-07-01,2018.0,52,Argentina,1369.0,CF,10.0,Left,3,4,5,Medium/Low,Normal (170-),Yes,NaN,"#Speedster, #Dribbler, #FK Specialist, #Acrobat, #Clinical Finisher, #Complete Forward","Finesse Shot, Speed Dribbler (AI), One Club Player, Team Player",93.0,89.0,86.0,96.0,27.0,63.0,84,94,71,89,85,96,89,90,76,96,96,90,94,94,95,80,73,77,60,88,48,22,92,90,76,NaN,25,21,20,6,11,15,14,8,NaN,89+3,89+3,89+3,92+3,90+3,90+3,90+3,92+3,92+3,92+3,92+3,90+3,79+3,79+3,79+3,90+3,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png,https://cdn.sofifa.net/teams/241/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/150002,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,79000000.0,375000.0,29,1985-02-05,185,80,243.0,Real Madrid CF,Spain Primera Division,1.0,LW,7.0,NaN,2009-07-01,2018.0,38,Portugal,1354.0,LW,7.0,Right,4,5,5,High/Low,Normal (185+),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat, #Clinical Finisher, #Complete Forward","Power Free-Kick, Flair, Long Shot Taker (AI), Speed Dribbler (AI)",93.0,93.0,81.0,91.0,32.0,79.0,83,95,86,82,87,93,88,79,72,92,91,94,93,90,63,94,94,89,79,93,63,24,91,81,85,NaN,22,31,23,7,11,15,14,11,NaN,91+1,91+1,91+1,89+3,91+1,91+1,91+1,89+3,89+3,89+3,89+3,87+3,77+3,77+3,77+3,87+3,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png,https://cdn.sofifa.net/teams/243/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
A. Robben,9014,https://sofifa.com/player/9014/arjen-robben/150002,Arjen Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,1984-01-23,180,80,21.0,FC Bayern München,German 1. Bundesliga,1.0,SUB,10.0,NaN,2009-08-28,2017.0,34,Netherlands,105035.0,RS,11.0,Left,2,4,5,High/Low,Normal (170-185),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat","Diver, Injury Prone, Avoids Using Weaker Foot, Selfish, Long Shot Taker (AI), Speed Dribbler (AI), Chip Shot (AI)",93.0,86.0,83.0,92.0,32.0,64.0,80,85,50,86,86,93,85,83,76,90,93,93,93,89,91,86,61,78,65,90,47,39,89,84,80,NaN,29,26,26,10,8,11,5,15,NaN,84+3,84+3,84+3,88+2,87+3,87+3,87+3,88+2,88+2,88+2,88+2,87+3,78+3,78+3,78+3,87+3,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/105035/60.png,https://cdn.sofifa.net/flags/nl.png
Z. Ibrahimović,41236,https://sofifa.com/player/41236/zlatan-ibrahimovic/150002,Zlatan Ibrahimović,ST,90,90,52500000.0,275000.0,32,1981-10-03,195,95,73.0,Paris Saint-Germain,French Ligue 1,1.0,ST,10.0,NaN,2012-07-01,2016.0,46,Sweden,1363.0,ST,10.0,Right,4,4,5,Medium/Low,Normal (185+),Yes,NaN,"#Poacher, #Aerial Threat, #Distance Shooter, #Acrobat, #Strength, #Clinical Finisher, #Complete Forward","Power Free-Kick, Leadership, Flair, Long Shot Taker (AI), Technical Dribbler (AI)",76.0,91.0,81.0,86.0,34.0,86.0,76,91,76,84,92,88,80,80,76,90,74,77,86,85,41,93,72,78,93,88,84,20,86,83,91,NaN,25,41,27,13,15,10,9,12,NaN,87+3,87+3,87+3,84+3,86+3,86+3,86+3,84+3,86+3,86+3,86+3,83+3,76+3,76+3,76+3,83+3,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1363/60.png,https://cdn.sofifa.net/flags/se.png
M. Neuer,167495,https://sofifa.com/player/167495/manuel-neuer/150002,Manuel Peter Neuer,GK,90,90,63500000.0,300000.0,28,1986-03-27,193,92,21.0,FC Bayern München,German 1. Bundesliga,1.0,GK,1.0,NaN,2011-07-01,2019.0,21,Germany,1337.0,GK,1.0,Right,4,1,5,Medium/Medium,Normal (185+),Yes,NaN,NaN,"GK Up for Corners, GK Long Throw, 1-on-1 Rush",NaN,NaN,NaN,NaN,NaN,NaN,25,25,25,42,25,25,25,25,41,31,58,61,43,89,35,42,78,44,83,25,29,30,25,20,37,NaN,25,25,25,87,85,92,90,86,60.0,38+3,38+3,38+3,36+3,37+3,37+3,37+3,36+3,36+3,36+3,36+3,38+3,36+3,36+3,36+3,38+3,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1337/60.png,https://cdn.sofifa.net/flags/de.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E. Redman,220806,https://sofifa.com/player/220806/ellis-redman/150002,Ellis Redman,CB,41,61,20000.0,2000.0,17,1996-09-26,187,81,112254.0,Newport County,English League Two,4.0,RES,35.0,NaN,2013-10-22,2015.0,50,Wales,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,66.0,25.0,29.0,30.0,39.0,53.0,25,25,41,36,25,25,21,25,33,26,65,66,52,36,55,22,62,56,52,25,50,41,25,22,31,NaN,38,40,35,12,6,15,8,6,NaN,32,32,32,33,30,30,30,33,30,30,30,34,32,32,32,34,37,38,38,38,37,40,41,41,41,40,10,https://cdn.sofifa.net/players/220/806/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
A. Collins,225509,https://sofifa.com/player/225509/aaron-collins/150002,Aaron Graham John Collins,ST,41,50,30000.0,2000.0,17,1997-06-01,178,57,112254.0,Newport County,English League Two,4.0,RES,39.0,NaN,2014-08-14,2015.0,50,Wales,NaN,NaN,NaN,Right,3,3,1,Medium/Medium,Lean (170-185),No,NaN,NaN,NaN,64.0,41.0,27.0,35.0,27.0,41.0,22,47,43,25,27,29,20,22,24,30,60,68,66,39,68,36,51,47,42,36,30,25,41,39,47,NaN,25,25,25,13,11,12,15,11,NaN,41,41,41,37,39,39,39,37,37,37,37,35,32,32,32,35,31,30,30,30,31,32,31,31,31,32,14,https://cdn.sofifa.net/players/225/509/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
P. Tisdale,201197,https://sofifa.com/player/201197/paul-tisdale/150002,Paul Tisdale,"CM, CAM",40,40,NaN,2000.0,41,1973-01-14,175,72,143.0,Exeter City,English League Two,4.0,RES,17.0,NaN,2006-06-26,2015.0,32,Malta,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,NaN,NaN,"Injury Prone, Playmaker (AI)",38.0,36.0,42.0,45.0,31.0,33.0,39,36,29,43,27,46,41,53,41,44,35,41,37,41,51,32,39,25,37,38,32,35,43,41,55,NaN,27,34,29,5,6,14,8,13,NaN,38,38,38,41-1,40,40,40,41-1,41-1,41-1,41-1,41-1,40,40,40,41-1,36,37,37,37,36,34,33,33,33,34,10,https://cdn.sofifa.net/players/201/197/15_120.png,https://cdn.sofifa.net/teams/143/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/mt.png
P. Żemło,217591,https://sofifa.com/player/217591/piotr-zemlo/150002,Piotr Żemło,"LM, LB",40,50,15000.0,2000.0,18,1995-07-10,190,76,1873.0,Wisła Kraków,Polish T-Mobile Ekstraklasa,1.0,RES,43.0,NaN,2012-07-01,2015.0,37,Poland,NaN,NaN,NaN,Left,3,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,58.0,27.0,35.0,31.0,52.0,68.0,49,24,57,40,25,27,24,21,34,32,57,58,36,50,44,31,61,74,75,25,44,47,38,21,31,NaN,54,52,51,8,14,7,10,9,NaN,38,38,38,38,35,35,35,38,33,33,33,40,38,38,38,40,48,46,46,46,48,51-1,53-3,53-3,53-3,51-1,12,https://cdn.sofifa.net/players/217/591/15_120.png,https://cdn.sofifa.net/teams/1873/60.png,https://cdn.sofifa.net/flags/pl.png,NaN,https://cdn.sofifa.net/flags/pl.png
T. Davies,222947,https://sofifa.com/player/222947/tom-davies/150002,Thomas Christopher Davies,CB,40,49,15000.0,2000.0,22,1992-04-18,180,70,112260.0,Fleetwood Town,English League One,3.0,RES,26.0,NaN,2014-03-11,2021.0,14,England,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (170-185),No,NaN,NaN,NaN,72.0,27.0,27.0,30.0,35.0,61.0,23,25,38,32,29,24,24,27,21,35,71,73,33,32,61,39,64,70,63,22,44,34,27,25,21,NaN,36,34,35,15,13,6,11,9,NaN,35,35,35,33,33,33,33,33,31,31,31,34,31,31,31,34,37,36,36,36,37,39,40,40,40,39,13,https://cdn.sofifa.net/players/222/947/15_120.png,https://cdn.sofifa.net/teams/112260/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-eng.png

In [26]:
df1.reset_index()

,index,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,0,158023,https://sofifa.com/player/158023/lionel-messi/150002,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,100500000.0,550000.0,27,1987-06-24,169,67,241.0,FC Barcelona,Spain Primera Division,1.0,CF,10.0,NaN,2004-07-01,2018.0,52,Argentina,1369.0,CF,10.0,Left,3,4,5,Medium/Low,Normal (170-),Yes,NaN,"#Speedster, #Dribbler, #FK Specialist, #Acrobat, #Clinical Finisher, #Complete Forward","Finesse Shot, Speed Dribbler (AI), One Club Player, Team Player",93.0,89.0,86.0,96.0,27.0,63.0,84,94,71,89,85,96,89,90,76,96,96,90,94,94,95,80,73,77,60,88,48,22,92,90,76,NaN,25,21,20,6,11,15,14,8,NaN,89+3,89+3,89+3,92+3,90+3,90+3,90+3,92+3,92+3,92+3,92+3,90+3,79+3,79+3,79+3,90+3,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png,https://cdn.sofifa.net/teams/241/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/150002,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,79000000.0,375000.0,29,1985-02-05,185,80,243.0,Real Madrid CF,Spain Primera Division,1.0,LW,7.0,NaN,2009-07-01,2018.0,38,Portugal,1354.0,LW,7.0,Right,4,5,5,High/Low,Normal (185+),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat, #Clinical Finisher, #Complete Forward","Power Free-Kick, Flair, Long Shot Taker (AI), Speed Dribbler (AI)",93.0,93.0,81.0,91.0,32.0,79.0,83,95,86,82,87,93,88,79,72,92,91,94,93,90,63,94,94,89,79,93,63,24,91,81,85,NaN,22,31,23,7,11,15,14,11,NaN,91+1,91+1,91+1,89+3,91+1,91+1,91+1,89+3,89+3,89+3,89+3,87+3,77+3,77+3,77+3,87+3,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png,https://cdn.sofifa.net/teams/243/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
2,2,9014,https://sofifa.com/player/9014/arjen-robben/150002,A. Robben,Arjen Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,1984-01-23,180,80,21.0,FC Bayern München,German 1. Bundesliga,1.0,SUB,10.0,NaN,2009-08-28,2017.0,34,Netherlands,105035.0,RS,11.0,Left,2,4,5,High/Low,Normal (170-185),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat","Diver, Injury Prone, Avoids Using Weaker Foot, Selfish, Long Shot Taker (AI), Speed Dribbler (AI), Chip Shot (AI)",93.0,86.0,83.0,92.0,32.0,64.0,80,85,50,86,86,93,85,83,76,90,93,93,93,89,91,86,61,78,65,90,47,39,89,84,80,NaN,29,26,26,10,8,11,5,15,NaN,84+3,84+3,84+3,88+2,87+3,87+3,87+3,88+2,88+2,88+2,88+2,87+3,78+3,78+3,78+3,87+3,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/105035/60.png,https://cdn.sofifa.net/flags/nl.png
3,3,41236,https://sofifa.com/player/41236/zlatan-ibrahimovic/150002,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,52500000.0,275000.0,32,1981-10-03,195,95,73.0,Paris Saint-Germain,French Ligue 1,1.0,ST,10.0,NaN,2012-07-01,2016.0,46,Sweden,1363.0,ST,10.0,Right,4,4,5,Medium/Low,Normal (185+),Yes,NaN,"#Poacher, #Aerial Threat, #Distance Shooter, #Acrobat, #Strength, #Clinical Finisher, #Complete Forward","Power Free-Kick, Leadership, Flair, Long Shot Taker (AI), Technical Dribbler (AI)",76.0,91.0,81.0,86.0,34.0,86.0,76,91,76,84,92,88,80,80,76,90,74,77,86,85,41,93,72,78,93,88,84,20,86,83,91,NaN,25,41,27,13,15,10,9,12,NaN,87+3,87+3,87+3,84+3,86+3,86+3,86+3,84+3,86+3,86+3,86+3,83+3,76+3,76+3,76+3,83+3,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1363/60.png,https://cdn.sofifa.net/flags/se.png
4,4,167495,https://sofifa.com/player/167495/manuel-neuer/150002,M. Neuer,Manuel Peter Neuer,GK,90,90,63500000.0,300000.0,28,1986-03-27,193,92,21.0,FC Bayern München,German 1. Bundesliga,1.0,GK,1.0,NaN,2011-07-01,2019.0,21,Germany,1337.0,GK,1.0,Right,4,1,5,Medium/Medium,Normal (185+),Yes,NaN,NaN,"GK Up for Corners, GK Long Throw, 1-on-1 Rush",NaN,NaN,NaN,NaN,NaN,NaN,25,25,25,42,25,25,25,25,41,31,58,61,43,89,35,42,78,44,83,25,29,30,25,20,37,NaN,25,25,25,87,85,92,90,86,60.0,38+3,38+3,38+3,36+3,37+3,37+3,37+3,36+3,36+3,36+3,36+3,38+3,36+3,36+3,36+3,38+3,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1337/60.png,https://cdn.sofifa.net/flags/de.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,16150,220806,https://sofifa.com/player/220806/ellis-redman/150002,E. Redman,Ellis Redman,CB,41,61,20000.0,2000.0,17,1996-09-26,187,81,112254.0,Newport County,English League Two,4.0,RES,35.0,NaN,2013-10-22,2015.0,50,Wales,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,66.0,25.0,29.0,30.0,39.0,53.0,25,25,41,36,25,25,21,25,33,26,65,66,52,36,55,22,62,56,52,25,50,41,25,22,31,NaN,38,40,35,12,6,15,8,6,NaN,32,32,32,33,30,30,30,33,30,30,30,34,32,32,32,34,37,38,38,38,37,40,41,41,41,40,10,https://cdn.sofifa.net/players/220/806/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16151,16151,225509,https://sofifa.com/player/225509/aaron-collins/150002,A. Collins,Aaron Graham John Collins,ST,41,50,30000.0,2000.0,17,1997-06-01,178,57,112254.0,Newport County,English League Two,4.0,RES,39.0,NaN,2014-08-14,2015.0,50,Wales,NaN,NaN,NaN,Right,3,3,1,Medium/Medium,Lean (170-185),No,NaN,NaN,NaN,64.0,41.0,27.0,35.0,27.0,41.0,22,47,43,25,27,29,20,22,24,30,60,68,66,39,68,36,51,47,42,36,30,25,41,39,47,NaN,25,25,25,13,11,12,15,11,NaN,41,41,41,37,39,39,39,37,37,37,37,35,32,32,32,35,31,30,30,30,31,32,31,31,31,32,14,https://cdn.sofifa.net/players/225/509/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16152,16152,201197,https://sofifa.com/player/201197/paul-tisdale/150002,P. Tisdale,Paul Tisdale,"CM, CAM",40,40,NaN,2000.0,41,1973-01-14,175,72,143.0,Exeter City,English League Two,4.0,RES,17.0,NaN,2006-06-26,2015.0,32,Malta,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,NaN,NaN,"Injury Prone, Playmaker (AI)",38.0,36.0,42.0,45.0,31.0,33.0,39,36,29,43,27,46,41,53,41,44,35,41,37,41,51,32,39,25,37,38,32,35,43,41,55,NaN,27,34,29,5,6,14,8,13,NaN,38,38,38,41-1,40,40,40,41-1,41-1,41-1,41-1,41-1,40,40,40,41-1,36,37,37,37,36,34,33,33,33,34,10,https://cdn.sofifa.net/players/201/197/15_120.png,https://cdn.sofifa.net/teams/143/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/mt.png
16153,16153,217591,https://sofifa.com/player/217591/piotr-zemlo/150002,P. Żemło,Piotr Żemło,"LM, LB",40,50,15000.0,2000.0,18,1995-07-10,190,76,1873.0,Wisła Kraków,Polish T-Mobile Ekstraklasa,1.0,RES,43.0,NaN,2012-07-01,2015.0,37,Poland,NaN,NaN,NaN,Left,3,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,58.0,27.0,35.0,31.0,52.0,68.0,49,24,57,40,25,27,24,21,34,32,57,58,36,50,44,31,61,74,75,25,44,47,38,21,31,NaN,54,52,51,8,14,7,10,9,NaN,38,38,38,38,35,35,35,38,33,33,33,40,38,38,38,40,48,46,46,46,48,51-1,53-3,53-3,53-3,51-1,12,https://cdn.sofifa.net/players/217/591/15_120.png,https://cdn.sofifa.net/teams/1873/60.png,https://cdn.sofifa.net/flags/pl.png,NaN,https://cdn.sofifa.net/flags/pl.png
16154,16154,222947,https://sofifa.com/player/222947/tom-davies/150002,T. Davies,Thomas Christopher Davies,CB,40,49,15000.0,2000.0,22,1992-04-18,180,70,112260.0,Fleetwood Town,English League One,3.0,RES,26.0,NaN,2014-03-11,2021.0,14,England,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (170-185),No,NaN,NaN,NaN,72.0,27.0,27.0,30.0,35.0,61.0,23,25,38,32,29,24,24,27,21,35,71,73,33,32,61,39,64,70,63,22,44,34,27,25,21,NaN,36,34,35,15,13,6,11,9,NaN,35,35,35,33,33,33,33,33,31,31,31,34,31,31,31,34,37,36,36,36,37,39,40,40,40,39,13,https://cdn.sofifa.net/players/222/947/15_120.png,https://cdn.sofifa.net/teams/112260/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-eng.png

In [28]:
df1.sort_index()

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/150002,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,100500000.0,550000.0,27,1987-06-24,169,67,241.0,FC Barcelona,Spain Primera Division,1.0,CF,10.0,NaN,2004-07-01,2018.0,52,Argentina,1369.0,CF,10.0,Left,3,4,5,Medium/Low,Normal (170-),Yes,NaN,"#Speedster, #Dribbler, #FK Specialist, #Acrobat, #Clinical Finisher, #Complete Forward","Finesse Shot, Speed Dribbler (AI), One Club Player, Team Player",93.0,89.0,86.0,96.0,27.0,63.0,84,94,71,89,85,96,89,90,76,96,96,90,94,94,95,80,73,77,60,88,48,22,92,90,76,NaN,25,21,20,6,11,15,14,8,NaN,89+3,89+3,89+3,92+3,90+3,90+3,90+3,92+3,92+3,92+3,92+3,90+3,79+3,79+3,79+3,90+3,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png,https://cdn.sofifa.net/teams/241/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/150002,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,79000000.0,375000.0,29,1985-02-05,185,80,243.0,Real Madrid CF,Spain Primera Division,1.0,LW,7.0,NaN,2009-07-01,2018.0,38,Portugal,1354.0,LW,7.0,Right,4,5,5,High/Low,Normal (185+),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat, #Clinical Finisher, #Complete Forward","Power Free-Kick, Flair, Long Shot Taker (AI), Speed Dribbler (AI)",93.0,93.0,81.0,91.0,32.0,79.0,83,95,86,82,87,93,88,79,72,92,91,94,93,90,63,94,94,89,79,93,63,24,91,81,85,NaN,22,31,23,7,11,15,14,11,NaN,91+1,91+1,91+1,89+3,91+1,91+1,91+1,89+3,89+3,89+3,89+3,87+3,77+3,77+3,77+3,87+3,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png,https://cdn.sofifa.net/teams/243/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
2,9014,https://sofifa.com/player/9014/arjen-robben/150002,A. Robben,Arjen Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,1984-01-23,180,80,21.0,FC Bayern München,German 1. Bundesliga,1.0,SUB,10.0,NaN,2009-08-28,2017.0,34,Netherlands,105035.0,RS,11.0,Left,2,4,5,High/Low,Normal (170-185),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat","Diver, Injury Prone, Avoids Using Weaker Foot, Selfish, Long Shot Taker (AI), Speed Dribbler (AI), Chip Shot (AI)",93.0,86.0,83.0,92.0,32.0,64.0,80,85,50,86,86,93,85,83,76,90,93,93,93,89,91,86,61,78,65,90,47,39,89,84,80,NaN,29,26,26,10,8,11,5,15,NaN,84+3,84+3,84+3,88+2,87+3,87+3,87+3,88+2,88+2,88+2,88+2,87+3,78+3,78+3,78+3,87+3,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/105035/60.png,https://cdn.sofifa.net/flags/nl.png
3,41236,https://sofifa.com/player/41236/zlatan-ibrahimovic/150002,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,52500000.0,275000.0,32,1981-10-03,195,95,73.0,Paris Saint-Germain,French Ligue 1,1.0,ST,10.0,NaN,2012-07-01,2016.0,46,Sweden,1363.0,ST,10.0,Right,4,4,5,Medium/Low,Normal (185+),Yes,NaN,"#Poacher, #Aerial Threat, #Distance Shooter, #Acrobat, #Strength, #Clinical Finisher, #Complete Forward","Power Free-Kick, Leadership, Flair, Long Shot Taker (AI), Technical Dribbler (AI)",76.0,91.0,81.0,86.0,34.0,86.0,76,91,76,84,92,88,80,80,76,90,74,77,86,85,41,93,72,78,93,88,84,20,86,83,91,NaN,25,41,27,13,15,10,9,12,NaN,87+3,87+3,87+3,84+3,86+3,86+3,86+3,84+3,86+3,86+3,86+3,83+3,76+3,76+3,76+3,83+3,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1363/60.png,https://cdn.sofifa.net/flags/se.png
4,167495,https://sofifa.com/player/167495/manuel-neuer/150002,M. Neuer,Manuel Peter Neuer,GK,90,90,63500000.0,300000.0,28,1986-03-27,193,92,21.0,FC Bayern München,German 1. Bundesliga,1.0,GK,1.0,NaN,2011-07-01,2019.0,21,Germany,1337.0,GK,1.0,Right,4,1,5,Medium/Medium,Normal (185+),Yes,NaN,NaN,"GK Up for Corners, GK Long Throw, 1-on-1 Rush",NaN,NaN,NaN,NaN,NaN,NaN,25,25,25,42,25,25,25,25,41,31,58,61,43,89,35,42,78,44,83,25,29,30,25,20,37,NaN,25,25,25,87,85,92,90,86,60.0,38+3,38+3,38+3,36+3,37+3,37+3,37+3,36+3,36+3,36+3,36+3,38+3,36+3,36+3,36+3,38+3,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1337/60.png,https://cdn.sofifa.net/flags/de.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,220806,https://sofifa.com/player/220806/ellis-redman/150002,E. Redman,Ellis Redman,CB,41,61,20000.0,2000.0,17,1996-09-26,187,81,112254.0,Newport County,English League Two,4.0,RES,35.0,NaN,2013-10-22,2015.0,50,Wales,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,66.0,25.0,29.0,30.0,39.0,53.0,25,25,41,36,25,25,21,25,33,26,65,66,52,36,55,22,62,56,52,25,50,41,25,22,31,NaN,38,40,35,12,6,15,8,6,NaN,32,32,32,33,30,30,30,33,30,30,30,34,32,32,32,34,37,38,38,38,37,40,41,41,41,40,10,https://cdn.sofifa.net/players/220/806/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16151,225509,https://sofifa.com/player/225509/aaron-collins/150002,A. Collins,Aaron Graham John Collins,ST,41,50,30000.0,2000.0,17,1997-06-01,178,57,112254.0,Newport County,English League Two,4.0,RES,39.0,NaN,2014-08-14,2015.0,50,Wales,NaN,NaN,NaN,Right,3,3,1,Medium/Medium,Lean (170-185),No,NaN,NaN,NaN,64.0,41.0,27.0,35.0,27.0,41.0,22,47,43,25,27,29,20,22,24,30,60,68,66,39,68,36,51,47,42,36,30,25,41,39,47,NaN,25,25,25,13,11,12,15,11,NaN,41,41,41,37,39,39,39,37,37,37,37,35,32,32,32,35,31,30,30,30,31,32,31,31,31,32,14,https://cdn.sofifa.net/players/225/509/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16152,201197,https://sofifa.com/player/201197/paul-tisdale/150002,P. Tisdale,Paul Tisdale,"CM, CAM",40,40,NaN,2000.0,41,1973-01-14,175,72,143.0,Exeter City,English League Two,4.0,RES,17.0,NaN,2006-06-26,2015.0,32,Malta,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,NaN,NaN,"Injury Prone, Playmaker (AI)",38.0,36.0,42.0,45.0,31.0,33.0,39,36,29,43,27,46,41,53,41,44,35,41,37,41,51,32,39,25,37,38,32,35,43,41,55,NaN,27,34,29,5,6,14,8,13,NaN,38,38,38,41-1,40,40,40,41-1,41-1,41-1,41-1,41-1,40,40,40,41-1,36,37,37,37,36,34,33,33,33,34,10,https://cdn.sofifa.net/players/201/197/15_120.png,https://cdn.sofifa.net/teams/143/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/mt.png
16153,217591,https://sofifa.com/player/217591/piotr-zemlo/150002,P. Żemło,Piotr Żemło,"LM, LB",40,50,15000.0,2000.0,18,1995-07-10,190,76,1873.0,Wisła Kraków,Polish T-Mobile Ekstraklasa,1.0,RES,43.0,NaN,2012-07-01,2015.0,37,Poland,NaN,NaN,NaN,Left,3,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,58.0,27.0,35.0,31.0,52.0,68.0,49,24,57,40,25,27,24,21,34,32,57,58,36,50,44,31,61,74,75,25,44,47,38,21,31,NaN,54,52,51,8,14,7,10,9,NaN,38,38,38,38,35,35,35,38,33,33,33,40,38,38,38,40,48,46,46,46,48,51-1,53-3,53-3,53-3,51-1,12,https://cdn.sofifa.net/players/217/591/15_120.png,https://cdn.sofifa.net/teams/1873/60.png,https://cdn.sofifa.net/flags/pl.png,NaN,https://cdn.sofifa.net/flags/pl.png
16154,222947,https://sofifa.com/player/222947/tom-davies/150002,T. Davies,Thomas Christopher Davies,CB,40,49,15000.0,2000.0,22,1992-04-18,180,70,112260.0,Fleetwood Town,English League One,3.0,RES,26.0,NaN,2014-03-11,2021.0,14,England,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (170-185),No,NaN,NaN,NaN,72.0,27.0,27.0,30.0,35.0,61.0,23,25,38,32,29,24,24,27,21,35,71,73,33,32,61,39,64,70,63,22,44,34,27,25,21,NaN,36,34,35,15,13,6,11,9,NaN,35,35,35,33,33,33,33,33,31,31,31,34,31,31,31,34,37,36,36,36,37,39,40,40,40,39,13,https://cdn.sofifa.net/players/222/947/15_120.png,https://cdn.sofifa.net/teams/112260/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-eng.png

In [30]:
df1.sort_index(inplace = True)
df1

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/150002,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,100500000.0,550000.0,27,1987-06-24,169,67,241.0,FC Barcelona,Spain Primera Division,1.0,CF,10.0,NaN,2004-07-01,2018.0,52,Argentina,1369.0,CF,10.0,Left,3,4,5,Medium/Low,Normal (170-),Yes,NaN,"#Speedster, #Dribbler, #FK Specialist, #Acrobat, #Clinical Finisher, #Complete Forward","Finesse Shot, Speed Dribbler (AI), One Club Player, Team Player",93.0,89.0,86.0,96.0,27.0,63.0,84,94,71,89,85,96,89,90,76,96,96,90,94,94,95,80,73,77,60,88,48,22,92,90,76,NaN,25,21,20,6,11,15,14,8,NaN,89+3,89+3,89+3,92+3,90+3,90+3,90+3,92+3,92+3,92+3,92+3,90+3,79+3,79+3,79+3,90+3,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png,https://cdn.sofifa.net/teams/241/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/150002,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,79000000.0,375000.0,29,1985-02-05,185,80,243.0,Real Madrid CF,Spain Primera Division,1.0,LW,7.0,NaN,2009-07-01,2018.0,38,Portugal,1354.0,LW,7.0,Right,4,5,5,High/Low,Normal (185+),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat, #Clinical Finisher, #Complete Forward","Power Free-Kick, Flair, Long Shot Taker (AI), Speed Dribbler (AI)",93.0,93.0,81.0,91.0,32.0,79.0,83,95,86,82,87,93,88,79,72,92,91,94,93,90,63,94,94,89,79,93,63,24,91,81,85,NaN,22,31,23,7,11,15,14,11,NaN,91+1,91+1,91+1,89+3,91+1,91+1,91+1,89+3,89+3,89+3,89+3,87+3,77+3,77+3,77+3,87+3,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png,https://cdn.sofifa.net/teams/243/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
2,9014,https://sofifa.com/player/9014/arjen-robben/150002,A. Robben,Arjen Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,1984-01-23,180,80,21.0,FC Bayern München,German 1. Bundesliga,1.0,SUB,10.0,NaN,2009-08-28,2017.0,34,Netherlands,105035.0,RS,11.0,Left,2,4,5,High/Low,Normal (170-185),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat","Diver, Injury Prone, Avoids Using Weaker Foot, Selfish, Long Shot Taker (AI), Speed Dribbler (AI), Chip Shot (AI)",93.0,86.0,83.0,92.0,32.0,64.0,80,85,50,86,86,93,85,83,76,90,93,93,93,89,91,86,61,78,65,90,47,39,89,84,80,NaN,29,26,26,10,8,11,5,15,NaN,84+3,84+3,84+3,88+2,87+3,87+3,87+3,88+2,88+2,88+2,88+2,87+3,78+3,78+3,78+3,87+3,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/105035/60.png,https://cdn.sofifa.net/flags/nl.png
3,41236,https://sofifa.com/player/41236/zlatan-ibrahimovic/150002,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,52500000.0,275000.0,32,1981-10-03,195,95,73.0,Paris Saint-Germain,French Ligue 1,1.0,ST,10.0,NaN,2012-07-01,2016.0,46,Sweden,1363.0,ST,10.0,Right,4,4,5,Medium/Low,Normal (185+),Yes,NaN,"#Poacher, #Aerial Threat, #Distance Shooter, #Acrobat, #Strength, #Clinical Finisher, #Complete Forward","Power Free-Kick, Leadership, Flair, Long Shot Taker (AI), Technical Dribbler (AI)",76.0,91.0,81.0,86.0,34.0,86.0,76,91,76,84,92,88,80,80,76,90,74,77,86,85,41,93,72,78,93,88,84,20,86,83,91,NaN,25,41,27,13,15,10,9,12,NaN,87+3,87+3,87+3,84+3,86+3,86+3,86+3,84+3,86+3,86+3,86+3,83+3,76+3,76+3,76+3,83+3,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1363/60.png,https://cdn.sofifa.net/flags/se.png
4,167495,https://sofifa.com/player/167495/manuel-neuer/150002,M. Neuer,Manuel Peter Neuer,GK,90,90,63500000.0,300000.0,28,1986-03-27,193,92,21.0,FC Bayern München,German 1. Bundesliga,1.0,GK,1.0,NaN,2011-07-01,2019.0,21,Germany,1337.0,GK,1.0,Right,4,1,5,Medium/Medium,Normal (185+),Yes,NaN,NaN,"GK Up for Corners, GK Long Throw, 1-on-1 Rush",NaN,NaN,NaN,NaN,NaN,NaN,25,25,25,42,25,25,25,25,41,31,58,61,43,89,35,42,78,44,83,25,29,30,25,20,37,NaN,25,25,25,87,85,92,90,86,60.0,38+3,38+3,38+3,36+3,37+3,37+3,37+3,36+3,36+3,36+3,36+3,38+3,36+3,36+3,36+3,38+3,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1337/60.png,https://cdn.sofifa.net/flags/de.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,220806,https://sofifa.com/player/220806/ellis-redman/150002,E. Redman,Ellis Redman,CB,41,61,20000.0,2000.0,17,1996-09-26,187,81,112254.0,Newport County,English League Two,4.0,RES,35.0,NaN,2013-10-22,2015.0,50,Wales,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,66.0,25.0,29.0,30.0,39.0,53.0,25,25,41,36,25,25,21,25,33,26,65,66,52,36,55,22,62,56,52,25,50,41,25,22,31,NaN,38,40,35,12,6,15,8,6,NaN,32,32,32,33,30,30,30,33,30,30,30,34,32,32,32,34,37,38,38,38,37,40,41,41,41,40,10,https://cdn.sofifa.net/players/220/806/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16151,225509,https://sofifa.com/player/225509/aaron-collins/150002,A. Collins,Aaron Graham John Collins,ST,41,50,30000.0,2000.0,17,1997-06-01,178,57,112254.0,Newport County,English League Two,4.0,RES,39.0,NaN,2014-08-14,2015.0,50,Wales,NaN,NaN,NaN,Right,3,3,1,Medium/Medium,Lean (170-185),No,NaN,NaN,NaN,64.0,41.0,27.0,35.0,27.0,41.0,22,47,43,25,27,29,20,22,24,30,60,68,66,39,68,36,51,47,42,36,30,25,41,39,47,NaN,25,25,25,13,11,12,15,11,NaN,41,41,41,37,39,39,39,37,37,37,37,35,32,32,32,35,31,30,30,30,31,32,31,31,31,32,14,https://cdn.sofifa.net/players/225/509/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png
16152,201197,https://sofifa.com/player/201197/paul-tisdale/150002,P. Tisdale,Paul Tisdale,"CM, CAM",40,40,NaN,2000.0,41,1973-01-14,175,72,143.0,Exeter City,English League Two,4.0,RES,17.0,NaN,2006-06-26,2015.0,32,Malta,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,NaN,NaN,"Injury Prone, Playmaker (AI)",38.0,36.0,42.0,45.0,31.0,33.0,39,36,29,43,27,46,41,53,41,44,35,41,37,41,51,32,39,25,37,38,32,35,43,41,55,NaN,27,34,29,5,6,14,8,13,NaN,38,38,38,41-1,40,40,40,41-1,41-1,41-1,41-1,41-1,40,40,40,41-1,36,37,37,37,36,34,33,33,33,34,10,https://cdn.sofifa.net/players/201/197/15_120.png,https://cdn.sofifa.net/teams/143/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/mt.png
16153,217591,https://sofifa.com/player/217591/piotr-zemlo/150002,P. Żemło,Piotr Żemło,"LM, LB",40,50,15000.0,2000.0,18,1995-07-10,190,76,1873.0,Wisła Kraków,Polish T-Mobile Ekstraklasa,1.0,RES,43.0,NaN,2012-07-01,2015.0,37,Poland,NaN,NaN,NaN,Left,3,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,58.0,27.0,35.0,31.0,52.0,68.0,49,24,57,40,25,27,24,21,34,32,57,58,36,50,44,31,61,74,75,25,44,47,38,21,31,NaN,54,52,51,8,14,7,10,9,NaN,38,38,38,38,35,35,35,38,33,33,33,40,38,38,38,40,48,46,46,46,48,51-1,53-3,53-3,53-3,51-1,12,https://cdn.sofifa.net/players/217/591/15_120.png,https://cdn.sofifa.net/teams/1873/60.png,https://cdn.sofifa.net/flags/pl.png,NaN,https://cdn.sofifa.net/flags/pl.png
16154,222947,https://sofifa.com/player/222947/tom-davies/150002,T. Davies,Thomas Christopher Davies,CB,40,49,15000.0,2000.0,22,1992-04-18,180,70,112260.0,Fleetwood Town,English League One,3.0,RES,26.0,NaN,2014-03-11,2021.0,14,England,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (170-185),No,NaN,NaN,NaN,72.0,27.0,27.0,30.0,35.0,61.0,23,25,38,32,29,24,24,27,21,35,71,73,33,32,61,39,64,70,63,22,44,34,27,25,21,NaN,36,34,35,15,13,6,11,9,NaN,35,35,35,33,33,33,33,33,31,31,31,34,31,31,31,34,37,36,36,36,37,39,40,40,40,39,13,https://cdn.sofifa.net/players/222/947/15_120.png,https://cdn.sofifa.net/teams/112260/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-eng.png

In [42]:
df1[["人口","面积","2","3","4","5","6"]] = df1["player_url"].str.split("/", expand = True)
df1

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url,人口,面积,2,3,4,5,6
0,158023,https://sofifa.com/player/158023/lionel-messi/150002,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,100500000.0,550000.0,27,1987-06-24,169,67,241.0,FC Barcelona,Spain Primera Division,1.0,CF,10.0,NaN,2004-07-01,2018.0,52,Argentina,1369.0,CF,10.0,Left,3,4,5,Medium/Low,Normal (170-),Yes,NaN,"#Speedster, #Dribbler, #FK Specialist, #Acrobat, #Clinical Finisher, #Complete Forward","Finesse Shot, Speed Dribbler (AI), One Club Player, Team Player",93.0,89.0,86.0,96.0,27.0,63.0,84,94,71,89,85,96,89,90,76,96,96,90,94,94,95,80,73,77,60,88,48,22,92,90,76,NaN,25,21,20,6,11,15,14,8,NaN,89+3,89+3,89+3,92+3,90+3,90+3,90+3,92+3,92+3,92+3,92+3,90+3,79+3,79+3,79+3,90+3,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png,https://cdn.sofifa.net/teams/241/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png,https:,,sofifa.com,player,158023,lionel-messi,150002
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/150002,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,79000000.0,375000.0,29,1985-02-05,185,80,243.0,Real Madrid CF,Spain Primera Division,1.0,LW,7.0,NaN,2009-07-01,2018.0,38,Portugal,1354.0,LW,7.0,Right,4,5,5,High/Low,Normal (185+),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat, #Clinical Finisher, #Complete Forward","Power Free-Kick, Flair, Long Shot Taker (AI), Speed Dribbler (AI)",93.0,93.0,81.0,91.0,32.0,79.0,83,95,86,82,87,93,88,79,72,92,91,94,93,90,63,94,94,89,79,93,63,24,91,81,85,NaN,22,31,23,7,11,15,14,11,NaN,91+1,91+1,91+1,89+3,91+1,91+1,91+1,89+3,89+3,89+3,89+3,87+3,77+3,77+3,77+3,87+3,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png,https://cdn.sofifa.net/teams/243/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png,https:,,sofifa.com,player,20801,c-ronaldo-dos-santos-aveiro,150002
2,9014,https://sofifa.com/player/9014/arjen-robben/150002,A. Robben,Arjen Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,1984-01-23,180,80,21.0,FC Bayern München,German 1. Bundesliga,1.0,SUB,10.0,NaN,2009-08-28,2017.0,34,Netherlands,105035.0,RS,11.0,Left,2,4,5,High/Low,Normal (170-185),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat","Diver, Injury Prone, Avoids Using Weaker Foot, Selfish, Long Shot Taker (AI), Speed Dribbler (AI), Chip Shot (AI)",93.0,86.0,83.0,92.0,32.0,64.0,80,85,50,86,86,93,85,83,76,90,93,93,93,89,91,86,61,78,65,90,47,39,89,84,80,NaN,29,26,26,10,8,11,5,15,NaN,84+3,84+3,84+3,88+2,87+3,87+3,87+3,88+2,88+2,88+2,88+2,87+3,78+3,78+3,78+3,87+3,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/105035/60.png,https://cdn.sofifa.net/flags/nl.png,https:,,sofifa.com,player,9014,arjen-robben,150002
3,41236,https://sofifa.com/player/41236/zlatan-ibrahimovic/150002,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,52500000.0,275000.0,32,1981-10-03,195,95,73.0,Paris Saint-Germain,French Ligue 1,1.0,ST,10.0,NaN,2012-07-01,2016.0,46,Sweden,1363.0,ST,10.0,Right,4,4,5,Medium/Low,Normal (185+),Yes,NaN,"#Poacher, #Aerial Threat, #Distance Shooter, #Acrobat, #Strength, #Clinical Finisher, #Complete Forward","Power Free-Kick, Leadership, Flair, Long Shot Taker (AI), Technical Dribbler (AI)",76.0,91.0,81.0,86.0,34.0,86.0,76,91,76,84,92,88,80,80,76,90,74,77,86,85,41,93,72,78,93,88,84,20,86,83,91,NaN,25,41,27,13,15,10,9,12,NaN,87+3,87+3,87+3,84+3,86+3,86+3,86+3,84+3,86+3,86+3,86+3,83+3,76+3,76+3,76+3,83+3,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1363/60.png,https://cdn.sofifa.net/flags/se.png,https:,,sofifa.com,player,41236,zlatan-ibrahimovic,150002
4,167495,https://sofifa.com/player/167495/manuel-neuer/150002,M. Neuer,Manuel Peter Neuer,GK,90,90,63500000.0,300000.0,28,1986-03-27,193,92,21.0,FC Bayern München,German 1. Bundesliga,1.0,GK,1.0,NaN,2011-07-01,2019.0,21,Germany,1337.0,GK,1.0,Right,4,1,5,Medium/Medium,Normal (185+),Yes,NaN,NaN,"GK Up for Corners, GK Long Throw, 1-on-1 Rush",NaN,NaN,NaN,NaN,NaN,NaN,25,25,25,42,25,25,25,25,41,31,58,61,43,89,35,42,78,44,83,25,29,30,25,20,37,NaN,25,25,25,87,85,92,90,86,60.0,38+3,38+3,38+3,36+3,37+3,37+3,37+3,36+3,36+3,36+3,36+3,38+3,36+3,36+3,36+3,38+3,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1337/60.png,https://cdn.sofifa.net/flags/de.png,https:,,sofifa.com,player,167495,manuel-neuer,150002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,220806,https://sofifa.com/player/220806/ellis-redman/150002,E. Redman,Ellis Redman,CB,41,61,20000.0,2000.0,17,1996-09-26,187,81,112254.0,Newport County,English League Two,4.0,RES,35.0,NaN,2013-10-22,2015.0,50,Wales,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,66.0,25.0,29.0,30.0,39.0,53.0,25,25,41,36,25,25,21,25,33,26,65,66,52,36,55,22,62,56,52,25,50,41,25,22,31,NaN,38,40,35,12,6,15,8,6,NaN,32,32,32,33,30,30,30,33,30,30,30,34,32,32,32,34,37,38,38,38,37,40,41,41,41,40,10,https://cdn.sofifa.net/players/220/806/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png,https:,,sofifa.com,player,220806,ellis-redman,150002
16151,225509,https://sofifa.com/player/225509/aaron-collins/150002,A. Collins,Aaron Graham John Collins,ST,41,50,30000.0,2000.0,17,1997-06-01,178,57,112254.0,Newport County,English League Two,4.0,RES,39.0,NaN,2014-08-14,2015.0,50,Wales,NaN,NaN,NaN,Right,3,3,1,Medium/Medium,Lean (170-185),No,NaN,NaN,NaN,64.0,41.0,27.0,35.0,27.0,41.0,22,47,43,25,27,29,20,22,24,30,60,68,66,39,68,36,51,47,42,36,30,25,41,39,47,NaN,25,25,25,13,11,12,15,11,NaN,41,41,41,37,39,39,39,37,37,37,37,35,32,32,32,35,31,30,30,30,31,32,31,31,31,32,14,https://cdn.sofifa.net/players/225/509/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png,https:,,sofifa.com,player,225509,aaron-collins,150002
16152,201197,https://sofifa.com/player/201197/paul-tisdale/150002,P. Tisdale,Paul Tisdale,"CM, CAM",40,40,NaN,2000.0,41,1973-01-14,175,72,143.0,Exeter City,English League Two,4.0,RES,17.0,NaN,2006-06-26,2015.0,32,Malta,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,NaN,NaN,"Injury Prone, Playmaker (AI)",38.0,36.0,42.0,45.0,31.0,33.0,39,36,29,43,27,46,41,53,41,44,35,41,37,41,51,32,39,25,37,38,32,35,43,41,55,NaN,27,34,29,5,6,14,8,13,NaN,38,38,38,41-1,40,40,40,41-1,41-1,41-1,41-1,41-1,40,40,40,41-1,36,37,37,37,36,34,33,33,33,34,10,https://cdn.sofifa.net/players/201/197/15_120.png,https://cdn.sofifa.net/teams/143/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/mt.png,https:,,sofifa.com,player,201197,paul-tisdale,150002
16153,217591,https://sofifa.com/player/217591/piotr-zemlo/150002,P. Żemło,Piotr Żemło,"LM, LB",40,50,15000.0,2000.0,18,1995-07-10,190,76,1873.0,Wisła Kraków,Polish T-Mobile Ekstraklasa,1.0,RES,43.0,NaN,2012-07-01,2015.0,37,Poland,NaN,NaN,NaN,Left,3,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,58.0,27.0,35.0,31.0,52.0,68.0,49,24,57,40,25,27,24,21,34,32,57,58,36,50,44,31,61,74,75,25,44,47,38,21,31,NaN,54,52,51,8,14,7,10,9,NaN,38,38,38,38,35,35,35,38,33,33,33,40,38,38,38,40,48,46,46,46,48,51-1,53-3,53-3,53-3,51-1,12,https://cdn.sofifa.net/players/217/591/15_120.png,https://cdn.sofifa.net/teams/1873/60.png,https://cdn.sofifa.net/flags/pl.png,NaN,https://cdn.sofifa.net/flags/pl.png,https:,,sofifa.com,player,217591,piotr-zemlo,150002
16154,222947,https://sofifa.com/player/222947/tom-davies/150002,T. Davies,Thomas Christopher Davies,CB,40,49,15000.0,2000.0,22,1992-04-18,180,70,112260.0,Fleetwood Town,English League One,3.0,RES,26.0,NaN,2014-03-11,2021.0,14,England,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (170-185),No,NaN,NaN,NaN,72.0,27.0,27.0,30.0,35.0,61.0,23,25,38,32,29,24,24,27,21,35,71,73,33,32,61,39,64,70,63,22,44,34,27,25,21,NaN,36,34,35,15,13,6,11,9,NaN,35,35,35,33,33,33,33,33,31,31,31,34,31,31,31,34,37,36,36,36,37,39,40,40,40,39,13,https://cdn.sofifa.net/players/222/947/15_120.png,https://cdn.sofifa.net/teams/112260/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-eng.png,https:,,sofifa.com,player,222947,tom-davies,150002

In [43]:
df1 = df1.drop("player_url", axis = 1)

In [44]:
df1

,sofifa_id,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url,人口,面积,2,3,4,5,6
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,100500000.0,550000.0,27,1987-06-24,169,67,241.0,FC Barcelona,Spain Primera Division,1.0,CF,10.0,NaN,2004-07-01,2018.0,52,Argentina,1369.0,CF,10.0,Left,3,4,5,Medium/Low,Normal (170-),Yes,NaN,"#Speedster, #Dribbler, #FK Specialist, #Acrobat, #Clinical Finisher, #Complete Forward","Finesse Shot, Speed Dribbler (AI), One Club Player, Team Player",93.0,89.0,86.0,96.0,27.0,63.0,84,94,71,89,85,96,89,90,76,96,96,90,94,94,95,80,73,77,60,88,48,22,92,90,76,NaN,25,21,20,6,11,15,14,8,NaN,89+3,89+3,89+3,92+3,90+3,90+3,90+3,92+3,92+3,92+3,92+3,90+3,79+3,79+3,79+3,90+3,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png,https://cdn.sofifa.net/teams/241/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png,https:,,sofifa.com,player,158023,lionel-messi,150002
1,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,79000000.0,375000.0,29,1985-02-05,185,80,243.0,Real Madrid CF,Spain Primera Division,1.0,LW,7.0,NaN,2009-07-01,2018.0,38,Portugal,1354.0,LW,7.0,Right,4,5,5,High/Low,Normal (185+),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat, #Clinical Finisher, #Complete Forward","Power Free-Kick, Flair, Long Shot Taker (AI), Speed Dribbler (AI)",93.0,93.0,81.0,91.0,32.0,79.0,83,95,86,82,87,93,88,79,72,92,91,94,93,90,63,94,94,89,79,93,63,24,91,81,85,NaN,22,31,23,7,11,15,14,11,NaN,91+1,91+1,91+1,89+3,91+1,91+1,91+1,89+3,89+3,89+3,89+3,87+3,77+3,77+3,77+3,87+3,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png,https://cdn.sofifa.net/teams/243/60.png,https://cdn.sofifa.net/flags/es.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png,https:,,sofifa.com,player,20801,c-ronaldo-dos-santos-aveiro,150002
2,9014,A. Robben,Arjen Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,1984-01-23,180,80,21.0,FC Bayern München,German 1. Bundesliga,1.0,SUB,10.0,NaN,2009-08-28,2017.0,34,Netherlands,105035.0,RS,11.0,Left,2,4,5,High/Low,Normal (170-185),Yes,NaN,"#Speedster, #Dribbler, #Distance Shooter, #Acrobat","Diver, Injury Prone, Avoids Using Weaker Foot, Selfish, Long Shot Taker (AI), Speed Dribbler (AI), Chip Shot (AI)",93.0,86.0,83.0,92.0,32.0,64.0,80,85,50,86,86,93,85,83,76,90,93,93,93,89,91,86,61,78,65,90,47,39,89,84,80,NaN,29,26,26,10,8,11,5,15,NaN,84+3,84+3,84+3,88+2,87+3,87+3,87+3,88+2,88+2,88+2,88+2,87+3,78+3,78+3,78+3,87+3,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/105035/60.png,https://cdn.sofifa.net/flags/nl.png,https:,,sofifa.com,player,9014,arjen-robben,150002
3,41236,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,52500000.0,275000.0,32,1981-10-03,195,95,73.0,Paris Saint-Germain,French Ligue 1,1.0,ST,10.0,NaN,2012-07-01,2016.0,46,Sweden,1363.0,ST,10.0,Right,4,4,5,Medium/Low,Normal (185+),Yes,NaN,"#Poacher, #Aerial Threat, #Distance Shooter, #Acrobat, #Strength, #Clinical Finisher, #Complete Forward","Power Free-Kick, Leadership, Flair, Long Shot Taker (AI), Technical Dribbler (AI)",76.0,91.0,81.0,86.0,34.0,86.0,76,91,76,84,92,88,80,80,76,90,74,77,86,85,41,93,72,78,93,88,84,20,86,83,91,NaN,25,41,27,13,15,10,9,12,NaN,87+3,87+3,87+3,84+3,86+3,86+3,86+3,84+3,86+3,86+3,86+3,83+3,76+3,76+3,76+3,83+3,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1363/60.png,https://cdn.sofifa.net/flags/se.png,https:,,sofifa.com,player,41236,zlatan-ibrahimovic,150002
4,167495,M. Neuer,Manuel Peter Neuer,GK,90,90,63500000.0,300000.0,28,1986-03-27,193,92,21.0,FC Bayern München,German 1. Bundesliga,1.0,GK,1.0,NaN,2011-07-01,2019.0,21,Germany,1337.0,GK,1.0,Right,4,1,5,Medium/Medium,Normal (185+),Yes,NaN,NaN,"GK Up for Corners, GK Long Throw, 1-on-1 Rush",NaN,NaN,NaN,NaN,NaN,NaN,25,25,25,42,25,25,25,25,41,31,58,61,43,89,35,42,78,44,83,25,29,30,25,20,37,NaN,25,25,25,87,85,92,90,86,60.0,38+3,38+3,38+3,36+3,37+3,37+3,37+3,36+3,36+3,36+3,36+3,38+3,36+3,36+3,36+3,38+3,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1337/60.png,https://cdn.sofifa.net/flags/de.png,https:,,sofifa.com,player,167495,manuel-neuer,150002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,220806,E. Redman,Ellis Redman,CB,41,61,20000.0,2000.0,17,1996-09-26,187,81,112254.0,Newport County,English League Two,4.0,RES,35.0,NaN,2013-10-22,2015.0,50,Wales,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,66.0,25.0,29.0,30.0,39.0,53.0,25,25,41,36,25,25,21,25,33,26,65,66,52,36,55,22,62,56,52,25,50,41,25,22,31,NaN,38,40,35,12,6,15,8,6,NaN,32,32,32,33,30,30,30,33,30,30,30,34,32,32,32,34,37,38,38,38,37,40,41,41,41,40,10,https://cdn.sofifa.net/players/220/806/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png,https:,,sofifa.com,player,220806,ellis-redman,150002
16151,225509,A. Collins,Aaron Graham John Collins,ST,41,50,30000.0,2000.0,17,1997-06-01,178,57,112254.0,Newport County,English League Two,4.0,RES,39.0,NaN,2014-08-14,2015.0,50,Wales,NaN,NaN,NaN,Right,3,3,1,Medium/Medium,Lean (170-185),No,NaN,NaN,NaN,64.0,41.0,27.0,35.0,27.0,41.0,22,47,43,25,27,29,20,22,24,30,60,68,66,39,68,36,51,47,42,36,30,25,41,39,47,NaN,25,25,25,13,11,12,15,11,NaN,41,41,41,37,39,39,39,37,37,37,37,35,32,32,32,35,31,30,30,30,31,32,31,31,31,32,14,https://cdn.sofifa.net/players/225/509/15_120.png,https://cdn.sofifa.net/teams/112254/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-wls.png,https:,,sofifa.com,player,225509,aaron-collins,150002
16152,201197,P. Tisdale,Paul Tisdale,"CM, CAM",40,40,NaN,2000.0,41,1973-01-14,175,72,143.0,Exeter City,English League Two,4.0,RES,17.0,NaN,2006-06-26,2015.0,32,Malta,NaN,NaN,NaN,Right,3,2,1,Medium/Medium,Lean (170-185),No,NaN,NaN,"Injury Prone, Playmaker (AI)",38.0,36.0,42.0,45.0,31.0,33.0,39,36,29,43,27,46,41,53,41,44,35,41,37,41,51,32,39,25,37,38,32,35,43,41,55,NaN,27,34,29,5,6,14,8,13,NaN,38,38,38,41-1,40,40,40,41-1,41-1,41-1,41-1,41-1,40,40,40,41-1,36,37,37,37,36,34,33,33,33,34,10,https://cdn.sofifa.net/players/201/197/15_120.png,https://cdn.sofifa.net/teams/143/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/mt.png,https:,,sofifa.com,player,201197,paul-tisdale,150002
16153,217591,P. Żemło,Piotr Żemło,"LM, LB",40,50,15000.0,2000.0,18,1995-07-10,190,76,1873.0,Wisła Kraków,Polish T-Mobile Ekstraklasa,1.0,RES,43.0,NaN,2012-07-01,2015.0,37,Poland,NaN,NaN,NaN,Left,3,2,1,Medium/Medium,Normal (185+),No,NaN,NaN,NaN,58.0,27.0,35.0,31.0,52.0,68.0,49,24,57,40,25,27,24,21,34,32,57,58,36,50,44,31,61,74,75,25,44,47,38,21,31,NaN,54,52,51,8,14,7,10,9,NaN,38,38,38,38,35,35,35,38,33,33,33,40,38,38,38,40,48,46,46,46,48,51-1,53-3,53-3,53-3,51-1,12,https://cdn.sofifa.net/players/217/591/15_120.png,https://cdn.sofifa.net/teams/1873/60.png,https://cdn.sofifa.net/flags/pl.png,NaN,https://cdn.sofifa.net/flags/pl.png,https:,,sofifa.com,player,217591,piotr-zemlo,150002
16154,222947,T. Davies,Thomas Christopher Davies,CB,40,49,15000.0,2000.0,22,1992-04-18,180,70,112260.0,Fleetwood Town,English League One,3.0,RES,26.0,NaN,2014-03-11,2021.0,14,England,NaN,NaN,NaN,Right,2,2,1,Medium/Medium,Normal (170-185),No,NaN,NaN,NaN,72.0,27.0,27.0,30.0,35.0,61.0,23,25,38,32,29,24,24,27,21,35,71,73,33,32,61,39,64,70,63,22,44,34,27,25,21,NaN,36,34,35,15,13,6,11,9,NaN,35,35,35,33,33,33,33,33,31,31,31,34,31,31,31,34,37,36,36,36,37,39,40,40,40,39,13,https://cdn.sofifa.net/players/222/947/15_120.png,https://cdn.sofifa.net/teams/112260/60.png,https://cdn.sofifa.net/flags/gb-eng.png,NaN,https://cdn.sofifa.net/flags/gb-eng.png,https:,,sofifa.com,player,222947,tom-davies,150002

In [46]:
df1[""].str.cat(df3["名"],sep="-")

KeyError: '姓'

In [47]:
pd.melt(df4,id_vars = ["国家代码", "年份"]), var_name = '年龄组', value_name = '肺结核病例数')

NameError: name 'df4' is not defined

In [1]:
df1["B"].fillna(0)#调用时所有NaN值都会被替换成传入的参数(0),还可以传入df4["B"].fillna(df["B"].mean())

NameError: name 'df1' is not defined

In [2]:
df5.dropna()#只要某一行时空缺的, 调用dropna就看不到它了
df5.dropna(subset = ["工资"],axis = 0,inplace = True)#删除存在缺失值的行,axis=0删除横行, axis=1时删除竖列
df5.drop_duplicates()#删除所有重复项
df5.drop_duplicates(subset= ["姓名","性别"])#

NameError: name 'df5' is not defined

In [3]:
df6 = pd.DataFrame({
    '姓名': ['John', 'Alice', 'Bob', 'Alice', 'John'],
    '年龄': [25, 30, 35, 30, 40],
    '性别': ['M', 'F', 'M', 'F', 'M']
})
df6

NameError: name 'pd' is not defined